### ISSUE TITLE
Show number of encounters per day

### ISSUE THREAD

**Issue by fluffyhoof** [corona-warn-app/cwa-wishlist#124]
It would be nice to see in the app how many (unique) encounters there are per day with other app users.
I see it more as kind of a fun feature in combination with supporting the current health measurements.

I'm wondering myself how many relevant encounters with other people I have per day during these strange times. Especially when you go outside for grocery shopping etc. it is hard to estimate. Maybe some people will be surprised to see that they have much more encounters than they thought they would have and are going to reduce it based on this information. 
If it is shown on a day to day basis similar to e.g. number of steps in the health app, you can see the impact of your actions and adjust them accordingly.

In addition it would show people that the app is really doing something (like it is also requested in issue #5 ).

Just an idea :)

**Comment by daimpi** [comment]
It is not possible for the App to do this, because:
 
1) the necessary information is not exposed to the App by the Google/Apple ENF : https://github.com/corona-warn-app/cwa-app-ios/issues/678#issuecomment-646686363
2) even if the data was exposed, you could not compute a number of contacts from it, as devices broadcast RPIs which change every 10-15 minutes: https://github.com/corona-warn-app/cwa-app-ios/issues/678#issuecomment-647128066

The app (or rather the whole pipeline) is designed with with the aim of archiving strong privacy protection, which o/c has tradeoffs wrt monitoring capabilities.

**Comment by fluffyhoof** [comment]
I see. Well, thanks for your answer.
Sorry, I wasn’t aware that this was already discussed
