### ISSUE TITLE
Erweiterung um Erfassung an Orten zu ermöglichen, wo zurzeit ein Datenblatt ausgefüllt werden muss

### ISSUE THREAD

**Issue by Frintrop** [corona-warn-app/cwa-wishlist#162]
## Feature description

In Restaurants, Schwimmbädern ect muss zurzeit immer ein Datenblatt für die Kontaktverfolgung ausgefüllt werden. Sicherer und besser wäre es an den Eingängen und Ausgängen der jeweiligen Örtlichkeit ein oder mehrere LE Bluetooth Empfänger zu installieren und mit einer erweiterten Version der Corona App, welche Tokens mit der Standard Corona App der Besucher austauscht.  Die erweitere Corona App könnte evt. die Tokens der Besucher mit Zeitstempel zur besseren Kontaktverfolgung abspeichern.

Yes

**Comment by sventuerpe** [comment]
Siehe auch #59, #70, #77

**Comment by GPclips** [comment]
Hello @Frintrop ,

thank you for reaching out to us. This issue is a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/138. 
Therefore I will continue and close this issue. Please follow up in thread https://github.com/corona-warn-app/cwa-wishlist/issues/138. 

Thanks,
LMM

Corona-Warn-App Open Source Team
