### ISSUE TITLE
Communicate directly via the app

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#165]
## Current Implementation
Currently, users can find the latest information (e.g. about problems) only through the [FAQ](https://www.coronawarn.app/en/faq/).

So f.e. if users under iOS 13.6 wonder why the App is not working, they have to go to the FAQ and find [this](https://www.coronawarn.app/en/faq/#iOS_136) answer. 
If the App would just show an info box on the main screen that this problem is known and solved with iOS 13.6.1, I assume that more users would see this and don't just say the App is not working but upgrade their iOS version. 

## Suggested Enhancement
I think it would be nice if users would be able to see more informations inside the App via f.e. an info box, etc.
The users should be able to close the box after they read it.

## Expected Benefits
It would be much easier for users to get important information, and it could be personalized better (e.g. not showing Android information to someone using iOS)

---

## Related Issues

- About showing local regulations: #151 
- Status page about the App's and the backend's _health_ : #134
- Understandable error messages: #112
- Report the context of an error: #17  

---
Internal Tracking ID: EXPOSUREAPP-2331

**Comment by GPclips** [comment]
Hello @Ein-Tim,

thanks for sharing your idea! I personally really like it. There is a thread about a similar topic, I like to link here: https://github.com/corona-warn-app/cwa-wishlist/issues/134 this was more about a status board, but similar in some way that both issues are describing ways to inform the users about the latest changes or important information in general.
I will transfer this issue to JIRA so that it gets in the hands of the right people.

Thanks you,
LMM

Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Thank you! @GPclips 
And thanks for all your quick and nice replies 👍

**Comment by daimpi** [comment]
Related issues: 
- https://github.com/corona-warn-app/cwa-wishlist/issues/17 
- https://github.com/corona-warn-app/cwa-wishlist/issues/112

I also really like @vaubaehn's idea [here](https://github.com/corona-warn-app/cwa-app-android/issues/998#issuecomment-682038554):
> Yes, my idea was going into a quite similar direction, I drew a primitive sketch about it -> [here](https://github.com/corona-warn-app/cwa-app-android/pull/864#issuecomment-674185410), but didn't take time yet for polishing and putting it into the wishlist repo.
> In short, I describe a **C**oncept **O**n **V**iewing **i**mportant **R**eliability **I**nformation of **D**evice = **COVirD** (to be pronounced: co-weird) ;)
> Sounds like a big thing to implement, but if some very small basics are set up first, it may be extended release by release (quite modular). So, if an error / exception / incompatibility would be detected, a card would show up, and link to in-app information or external FAQ. The 'root' card in main screen could provide genral information, if 'everything works fine' with CWA, and in case of problems it could be the starting point for finding information and solutions.

**Comment by itinance** [comment]
I second this and like to add something:

pls explain the actual meaning of Timestamps of a Matched Key in "Exposure Checks"-Detail Screen and tell the users, what it really is and what not. Because so many people believe that this timestamp will reflect the timestamp of the concrete Contact! I saw this in several discussions and a simple text label could avoid mis-interpretation here (and save time for those people that have to explain it several times). 

see also https://github.com/corona-warn-app/cwa-app-ios/issues/1245 for more information. Thx :)

**Comment by Ein-Tim** [comment]
Something what makes me really sad (there was also a discussion recently in the community slack: https://covidapps.slack.com/archives/C0194ML0MLN/p1608214559132100):

With 1.9.1 CWA updated to version 2 of the ENF. 
With that version it is possible that encounters are shown in the log but not in the App anymore. Also after the update user will see a drop in encounters: https://github.com/corona-warn-app/cwa-app-ios/issues/1703. This is very confusing and in combination with the matches shown in the Log, many users will think that this is a bug. 

There neither 2 new FAQ entries nor a blog post helps, since the normal user doesn't know about this (since the App does not inform the user that Blog and FAQ does exist... very sad)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> There neither 2 new FAQ entries nor a blog post helps, since the normal user doesn't know about this (since the App does not inform the user that Blog and FAQ does exist... very sad)

The FAQ section in the app links to the site of The Federal Government through `main_about_link`
https://www.bundesregierung.de/corona-warn-app-faq-englisch
https://www.bundesregierung.de/corona-warn-app-faq

The [English language page](https://www.bundesregierung.de/corona-warn-app-faq-englisch):
- prominently displays the telephone number of the technical hotline
- refers to version 1.7, not to version 1.9
- does not mention the Blog
- links to the German-language version of the FAQs https://www.coronawarn.app/de/faq/ (not the English language version) and the link is hidden in some of the individual questions and answers instead of being at the top of the page
- was last updated Monday, 19. October 2020

The [German language page](https://www.bundesregierung.de/corona-warn-app-faq):
- links to the FAQ https://www.coronawarn.app/de/faq/ & Blog https://www.coronawarn.app/de/blog/ at the top of the page
- does refer to Version 1.9
- says it was last updated on 25. November 2020

So, in summary, the German language page **does** give the user a route to the [Blog](https://www.coronawarn.app/de/blog/) and [FAQs](https://www.coronawarn.app/de/faq/), even though it is indirect.

The [English language page of the Federal Government](https://www.bundesregierung.de/corona-warn-app-faq-englisch) (https://www.bundesregierung.de/corona-warn-app-faq-englisch) needs some significant improvement. Perhaps the Open Source Team has some direct contact (or indirect contact through RKI) to request some improvement to the English language page? I did try a couple of weeks ago by using the [contact form](https://www.bundesregierung.de/breg-de/service/kontakt/kontakt) on this site, but I never got any response. 

I will add this specifically to the GitHub website issues so it can be passed one-to-one on to the other website owners of the Bundesregierung.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> So, in summary, the German language page does give the user a route to the Blog and FAQs, even though it is indirect.

Yes, but be honest: Will the normal user find this? No... 

> I will add this specifically to the GitHub website issues so it can be passed one-to-one on to the other website owners of the Bundesregierung.

Thank you!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> > So, in summary, the German language page does give the user a route to the Blog and FAQs, even though it is indirect.
> 
> Yes, but be honest: Will the normal user find this? No...

I share your concerns that the level of redirection to find information is too deep.

> > I will add this specifically to the GitHub website issues so it can be passed one-to-one on to the other website owners of the Bundesregierung.

I have created https://github.com/corona-warn-app/cwa-website/issues/711 now. At the least the available information should be helpful and current.

(BTW: I'm still not seeing CWA 1.9.1 in the Google Play Store.)

**Comment by Ein-Tim** [comment]
[This](https://twitter.com/EaeraAn/status/1535569275208990720?s=20&t=yU7zeZVPlWcSYke53NPBVw) user complains on Twitter about the following:
- No information in the app that positive rapid antigen self tests can't be added to the app
- and asks the question why [these](https://twitter.com/EaeraAn/status/1535569275208990720?s=20&t=yU7zeZVPlWcSYke53NPBVw) infos are not clearly in the app

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> No information in the app that positive rapid antigen self tests can't be added to the app

- Do you think that the FAQ article https://www.coronawarn.app/en/faq/results/#rat_tan_hotline should be expanded to mention also self-tests? 
- Also there is no explicit entry in the FAQ for self-tests. They are mentioned in https://www.coronawarn.app/en/faq/results/?search=&topic=glossary#glossary_rapid_antigen_test. Should there be a separate FAQ entry for self-tests (Antigen-Selbsttests)?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, I think it would be good to get this topic covered! Would you like to open an issue in the website repo for this?

However, as this is what the OP of this issue is a request to communicate directly via the app, I must say: It would be better if  this information could be found directly in the app.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Yes, I think it would be good to get this topic covered! Would you like to open an issue in the website repo for this?

- https://github.com/corona-warn-app/cwa-website/issues/3000 is now opened (by the way, quite incredible that we reached 3000 issues on the website!)

> However, as this is what the OP of this issue is a request to communicate directly via the app, I must say: It would be better if this information could be found directly in the app.

- It would be good if the section "Manage Your Tests" also included the information from https://www.coronawarn.app/en/faq/results/#rat_tan_hotline that a positive result from a Rapid Antigen Test, a Rapid PCR Test or a Selftest cannot be shared by TAN. It's essentially the same topic as I raised in https://github.com/corona-warn-app/cwa-documentation/issues/902, so maybe you could add your comment there or open a new topic so that the suggestion does not get lost.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I'll add a comment to the other issue.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
