### ISSUE TITLE
Provide an official interactive CWA dashboard with daily data (incl. data download)

### ISSUE THREAD

**Issue by micb25** [corona-warn-app/cwa-wishlist#236]
## Feature description

Since official [CWA data](https://www.coronawarn.app/assets/documents/2020-09-23-cwa-daten-fakten.pdf) is now available, please provide an official interactive dashboard presenting this data on a daily base.

## Problem and motivation

The current [CWA data](https://www.coronawarn.app/assets/documents/2020-09-23-cwa-daten-fakten.pdf) is presented in a PDF. In addition to an interactive dashboard, the raw data should be provided in a machine readable format (JSON, CSV) to allow further correlations like on my [dashboard](https://micb25.github.io/dka/).

## Is this something you're interested in working on

No, but I want to discontinue my unofficial CWA dashboard at [https://micb25.github.io/dka/](https://micb25.github.io/dka/). :-)

---
Internal Tracking ID: [EXPOSUREAPP-5018](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5018) (statistics overview)
Internal Tracking ID:  [EXPOSUREAPP-3674](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3674)

**Comment by alanrick** [comment]
@micb25 I consult your dashboard every day. It reassures me that the CWA efficiency is improving not declining so I'm truly grateful. 
Nevertheless, now that I've switched to the Irish app (which shows encouraging statistics within the app) I realize that having the statistics directly available from the app would be a huge win for the CWA app and thus worth doing.
It would also free your time for your other interests 😀

**Comment by MikeMcC399** [comment]
@alanrick 
Have you had any experience of the Irish app warning users spending time in Germany and encountering users of the German CWA app, who later test and report an infection?

**Comment by alanrick** [comment]
Nope. But the FAQ states it’s compatible and Telekom hotline confirmed that I can use it instead. Seeing as the CWA efficiency is still low I don’t have much to lose by trying it.

**Comment by MikeMcC399** [comment]
@alanrick 
How are you measuring "CWA efficiency" and why do you say it is lower than the Irish app?
Is this because the Irish app checks keys every 2 hours and CWA does it once a day?

Also there are a couple of other things to bear in mind:
### [EU Gateway FAQs](https://ec.europa.eu/info/sites/info/files/faqs_gateway_en.pdf)

>#### What about if I did a test in another EU country? 
>You can only insert a positive coronavirus test result in the app of the country where the test was taken. However, when you enter the code in that app, thanks to the interoperability, citizens from the country that you have visited will get notified that they have been in close contact of an infected case.

### Terms & Conditions of [COVID Tracker app - Republic of Ireland](https://covidtracker.gov.ie/)

>The COVID Tracker App is free to download and use to anyone who is living in or visiting the island of Ireland. The Services are intended only for people living in or visiting the island of Ireland and the Services may not be otherwise used.

**Comment by alanrick** [comment]
Thanks Mike,
I was already aware that I need to switch apps to scan the qrcode should I test but I'd missed the T&C clause. BTW another downside might be that the German providers may meter data-traffic for the Irish (and Italian) app whereas they exclude CWA from their metering (i.e. free).
The efficiency statement was based on the #150 thread, but in my case it's lower because of the [#916](https://github.com/corona-warn-app/cwa-app-ios/issues/916) issue which is why I switched.

**Comment by alanrick** [comment]
On Thursdays the RKI devotes a section in its central Situationsbericht (German version of the daily situation report)  to  the status of its Corona-Datenspende-App. The app is an interesting experiment but  no-one in their right mind would claim it is as strategically important as the CWA.

So I don't understand why this RKI report doesn't include the CWA status directly in their situation report.  This absence gives the impression the RKI has no interest in the CWA, even though they are meant to be engaged in it.

For the last 2 weeks the [efficacy of the CWA](https://micb25.github.io/dka/plots_de/plot_rki_cwa_cases_7d.png
) appears to have been decreasing, despite the political interest in exactly this kpi. 
No-one has attempted to explain why. Indeed, this deprecation may not even been noticed by the RKI. 

All in all, a reason for the RKI to provide a daily dashboard themselves, and summarize it in their daily situation reports instead of just a cursory overview elsewhere on their website.

![plot_rki_cwa_cases_7d](https://user-images.githubusercontent.com/7034358/99557641-33d6aa80-29c3-11eb-849e-a09c590cf477.png)
.

**Comment by dsarkar** [comment]
FYI - PR https://github.com/corona-warn-app/cwa-app-android/pull/2043

**Comment by Ein-Tim** [comment]
PR in the website repo: https://github.com/corona-warn-app/cwa-website/pull/1772

**Comment by Ein-Tim** [comment]
@micb25 

FYI: https://www.coronawarn.app/de/analysis/ is live now, showing some key figures, as test result sharing, downloads & warnings.

**Comment by dsarkar** [comment]
Dear @micb25 and community, thanks for contributing here! Best wishes, DS 

---
Corona-Warn-App Open Source Team
