### ISSUE TITLE
Day of CONTACT could improve cluster detection

### ISSUE THREAD

**Issue by stefanbode** [corona-warn-app/cwa-wishlist#247]
## Feature description
We should think if we add the contact date on any risk to the user as additional information. From a privacy point this should be acceptable as long as we only report the date. As far as I know, the date of the key is available. 

## Problem and motivation

The added information can help to influence the behavior in a positive way and also helps the Gesundheitsamt to detect the infection root more easily
## Is this something you're interested in working on

Yes

**Comment by Ein-Tim** [comment]
So @stefanbode I think you mean to show Days Since Encounter also for Low Risk ones, right? 
Please see #178. 
If you talk about showing the date of an Encounter and not the Days since it, please see #188 and [this](https://github.com/corona-warn-app/cwa-documentation/issues/433) Issue in the Documentation Repo.
Thanks!

**Comment by stefanbode** [comment]
Thanks for pointing out #178 and #188 which request quite similar things. Will work on these items and close this one.
