### ISSUE TITLE
Enable Labs to automatically warn if there is a positive test result 

### ISSUE THREAD

**Issue by ggjj11** [corona-warn-app/cwa-wishlist#256]
At the moment corona tests need to be scanned in by the person who was tested. This does not happen all the time - it would be desirable if the upload of the test result happened automatically after the test result is available. This would also speed up the detection of infection chains.

To enable labs to link the test with an instance of the corona app each test should have a unique  QR code which is (voluntarily) scanned by the app owner *prior* to submission of the sample to the lab. This way the lab can upload the test directly (instead of waiting for the test results being sent to the person who installed the app and this person needing to scan the QR code of the test).
If the default request is to please scan the QR code of the test prior to submission much more people will do it! This is the power of defaults! https://www.ted.com/talks/dan_ariely_are_we_in_control_of_our_own_decisions/up-next

**Comment by heinezen** [comment]
I think we can close this issue because the automatic upload of test result from lab->app was already implemented in the app's backend. For a discussion about opt-out of uploading keys, https://github.com/corona-warn-app/cwa-wishlist/issues/284 should be better place.

---
Corona-Warn-App Open Source Team
