### ISSUE TITLE
Inform/Remind user about different way to register a (positive) test

### ISSUE THREAD

**Issue by not-a-feature** [corona-warn-app/cwa-wishlist#270]
## Motivation and Background 
I work in a Lab that performs over 2000 PCR tests on SARS-CoV2 per day. I am in close contact with those that are calling people full time.

It came to our attention that patients try to add the test via QR-Code which doesn't work on about 500/day because the test-centre uses some other kind of "Ü-Schein" (neither the new 10C nor OEGD) which can't be registered by our system.
From those 500 patients, about 50-60 are positive and approx. 40 tried to scan the code / tried to add a positive result.

After calling them they are usually surprised that they can add the result anyway by calling the hotline.

## Current Implementation
After a failed QR-Code scan the user is notified with a popup. From this position, he/she can try again or aboard.

## Suggested Enhancements
**1)** After the failed scan, the user should be (visually) notified that there is a way to add a positive test result.
For example by highlighting the third card "Request TAN" with a greenish colour. Fading the colour in an out 2-3 times.

**2)** Create a push notification 24, 36, 48 hours after a
   - failed QR-Code scan. 
   - successful QR-Code scan if the test result isn't available yet. [Merged Idea from #287]
This notification should lead to a page where the user is informed about the other ways to get the test result and motivate him/her to add it via the teleTan.

## Expected Benefits
The users don't forget to add a positive test result. 

### Demo for 1)
something like that:
<img src="https://user-images.githubusercontent.com/25013642/99243176-959ae700-2800-11eb-814d-a82df0d356fb.gif" alt="GIF of a possible visual implementation" height=600>

---
Internal Tracking ID: [EXPOSUREAPP-5124](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5124)

**Comment by dsarkar** [comment]
Dear @not-a-feature ,

Thank you very much for this interesting proposal. We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-3953) in the internal Jira system. The developers will look into this issue now. Any further developments will be notified here in this Github issue.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Similar ideas from other issues:

* https://github.com/corona-warn-app/cwa-wishlist/issues/282 Visually separate UI for submitting test result and registering QR code
* https://github.com/corona-warn-app/cwa-wishlist/issues/287 Notification when no result is received for a few days + hint at TeleTAN

----
Corona-Warn-App Open Source Team

**Comment by achisto** [comment]
_I want to add some thoughts that were originally posted under issue #287. As @heinezen stated over there, these thoughts have already been added to the EXPOSUREAPP-3953 Jira-ticket. _

In my opinion there is another huge problem evolving around the whole teleTAN-process:

## Problem
When a user adds a test by scanning its QR-Code right after the testing procedure but that test's result is never transmitted to CWA they will not know that
- sometimes test results are not transmitted due to labs not connected to the CWA-infrastructure
- if a test result is not transmitted they are still able to warn their contacts

## Suggestion
There should be a notice on the "waiting for result" screen which reminds the user
- to contact local health authorities in case a result is not shown within e.g. 4 days
- that after receiving a positive result by phone/sms but **not** in CWA there is the option to request a teleTAN and warn contacts

Optional, that notice could only be shown after e.g. 3 days have passed since the test was added. In that case there should be a push-notification.

## Expected Benefits
I personally know two people, who received a positive result by SMS while the CWA didn't show the positive result for several days. Both did not know they could call the TAN-hotline and warn their contacts by requesting a teleTAN. 

There is no way of finding out about this alternative because not only does CWA fail to show a hint on the test-screen but, even worse, after having added the test there is no way of going back to the "add your result"-screen in order to find out about other verification methods. 

While there is still a significant number of labs not integrated into the CWA-infrastructure I am afraid that there could be a lot of people willing to share their result who simply don't know how to accomplish that. Adding a hint to the "waiting for result"-screen could significantly improve the number of people warning other users.

I originally published this issue as issue #287 three days ago along with a [Twitter-thread](https://twitter.com/achisto/status/1337867745527025664). In this thread I basically just explained what can also be found in the corresponding [FAQ-entry](https://www.coronawarn.app/de/faq/#qr_test) but was still surprised to see the thread being shared with several people experiencing the exact problem outlined above. These users did add their test by scanning the QR-code but never received a result and therefore thought that there's no way of warning others. This is a huge problem, especially because one could assume that users willing to add their test to CWA are also the ones willing to share their result.

**Comment by alanrick** [comment]
@not-a-feature Not wanting to detract from your great suggestion... but I'm curious about the remaining 1500 PCR tests that do rely on a 10C/OEGD form. 

According to the RKI CWA download statistics we can expect 20%-33% have the CWA checkbox ticked.  My suspicion is that the ratio is lower, because doctors surgeries and test-centers complete the form without the patient present and err on the side of caution (GDPR etc). 
My other suspicion is that it is a design bug that the this checkbox exists at all, and that all results should be fed (anonymously) into the result server and this won't impact privacy standards. [ I created a question about this ](https://github.com/corona-warn-app/cwa-documentation/issues/475)10 days ago but no-one has been able to answer it so far. 

I'd be very keen to hear your opinion, especially as to whether 300-500 of the 2000 PCR tests do indeed have the checkbox ticked.

**Comment by ndegendogo** [comment]
> According to the RKI CWA download statistics we can expect 20%-33% have the CWA checkbox ticked. 

@alanrick is there such a statistics? 

I am aware that the ratio of lab results available via cwa was disappointing low in late summer, for various reasons. Hopefully it is better now. 
The checkbox was one 'culprit', but there were many other reasons, like:
- not all labs using this form
- checkbox not ticked
- not all labs have software integrated with cwa infrastructure
- some labs had software that prints QR code wrongly and cwa cannot accept it

Several of these 'blockers' have been collected and addressed [here](https://github.com/corona-warn-app/cwa-documentation/issues/400)

**Comment by not-a-feature** [comment]
> but I'm curious about the remaining 1500 PCR tests that do rely on a 10C/OEGD form.

Good question, in our lab about 20-30% of the tests are registered online. There it depends, from which doctor we receive the "digital 10C/OEGD". Some doctors always mark the checkbox, some never. There aren't that many doctors in between.
The overall mean is about 25% checked. (I'll follow up with a more accurate number, but to do so I need to run a manual SQL-query, and due to, you know, data privacy, it has to be authorized)

The Remaining "print" forms are almost never checked. And often the lower part was not handed over to the patient. (We know because we receive both parts :facepalm: ...)
These come mainly from mobile test stations that test in nursing homes, asylum shelters and companies.

**Comment by not-a-feature** [comment]
I personally like the improvement mentioned in #287 to inform users about the teleTan if the test result isn't available after 24, 36 and 48 hours.
This will probably have the strongest impact.

**Comment by alanrick** [comment]
> > According to the RKI CWA download statistics we can expect 20%-33% have the CWA checkbox ticked.
> 
> @alanrick is there such a statistics?

Almost 24 million have downloaded the app. Germany has a population of 83 million. So assuming about 80% of those downloading activate the app, then about 20% have the App.  The 33% just a crude adjustment assuming that the youngest Germany (0-10) won't be tested as much as the others so the population getting tested is less than 83million. I assume CWA users are tested as much as non-CWA users so I'd expect 20-33% of the checkboxes to be ticked.

I'm aware of the other factors. The reminder function in 1.71 doesn't seem to have made a difference. According the [RKI statistics](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/Kennzahlen_11122020.pdf?__blob=publicationFile) the positive reporting rate is still only around 54% 

All I'm trying to investigate is the checkbox factor, which is why I'm asking @not-a-feature if the numbers tally or if there is a discrepancy indicating that the checkbox problem is a significant factor.

**Comment by alanrick** [comment]
Many thanks @not-a-feature 
The 25% mean does tally with my calculations indicating that there's nothing to worry about.  **On the other hand you say some doctors never check the boxes** and it's unlikely that they do this because _none_ of their patients have use the CWA. That does imply that the checkbox is problematic, and if it's not needed ([as I suggest](https://github.com/corona-warn-app/cwa-documentation/issues/475)) then it is reducing the efficiency unnecessarily and the efficiency of the app could be easily improved without even changing the code.

**Comment by alanrick** [comment]
> Some doctors always mark the checkbox, some never.
Wait! If some doctors _always_ mark the checkbox (and it's unlikely that all the patients have the app), then it sounds like those doctors have figured (and demonstrated) that there's no harm done by pumping _all_ results into the App's server. The sole role of the checkbox is to reduce the efficiency of the app.

**Comment by ndegendogo** [comment]
> If some doctors always mark the checkbox (and it's unlikely that all the patients have the app)

@alanrick the checkbox does not indicate that somebody has the app.
The checkbox does indicate that the person tested *consents to her results being uploaded to the server*.
Of course we can now speculate if those doctors always marking take their time and convince all their patients to mark the box.
Or if they just mark it by default, and nobody complains.

**Comment by GisoSchroederSAP** [comment]
@not-a-feature : After heavily investigating possible root causes for failed QR codes scans I's like to ask if you still observe that much persons that struggle with the registration process via QR code or with the "share your test result part of the process?
The reason is, that during the last weeks and releases evolved in many ways regarding the information and usability of these steps.
There is, however, a major not yet finally solved piece - the digital return of test results from the labs into the CWA infrastructure. Meanwhile, we contacted all major chains of medical facilities to pay special attention in reliability and performance of the  technical interface. After investigating hundreds of cases it turns out, apparently they lost focus in this areas. 
Therefore, we take this very seriously and "monitor" the output of the labs on a regular basis.

If you still experience large numbers of failed QR code scans, I kindly ask you to provide evidence and details (even multiple samples) to the community mailbox: corona-warn-app.opensource@sap.com 
We will investigate 

Many thanks in advance!

**Comment by not-a-feature** [comment]
Hi, 
I'll ask around and give you an update as soon as I know more

**Comment by GisoSchroederSAP** [comment]
> Hi,
> I'll ask around and give you an update as soon as I know more

Thanks for that, much appreciated.

**Comment by not-a-feature** [comment]
In the last weeks, the number of tests dropped significantly (only about 500-750 p.d.). Therefore the following finding may be distorted and/or not representative. 

- About 50% of these tests are done completely by ourself. There the QR-Code / CWA works flawlessly. 
- We (almost) don't get any samples from family-doctors anymore. Therefore I can't say anything about it. 
- The problem with the unchecked checkbox and the QR codes not being handed out persists, BUT it only happens with tests done by the red cross in nursing homes (nobody uses the app there). Due to the new testing strategy of Baden-Würtemberg, most of the tests done there are rapid antigen tests. Only if there is an "Ausbruchsgeschehen" we get the specimen. As this is happening very rarely this issue almost loses completely the relevance. 

Overall I would say that everything got a little bit better.

**Comment by alanrick** [comment]
>  if there is an "Ausbruchsgeschehen" we get the specimen. **As this is happening very rarely...** 
Very encouraging. The outbreaks in care homes has been the main source of infections in my locality.

The RKI skipped publishing the CWA statistics yet again (demoralizing) so I guess we'll have to wait a little longer for conformation of what you suspect.

**Comment by GisoSchroederSAP** [comment]
In case, there are non-10C/OEGD-Qr-Code used, would you be able to provide samples of those and the source, i.e., where they come from?

To be honest, we already are in contact with mobile emergency service teams (DRK Katastrophenschutz), those meanwhile are able to add perfectly fitting QR-Codes to their individual forms on-the-fly (we tested with labs already), so there should be no necessity to go, even when the testing was forced by health authority (Gesundheitsamt) with Ü-Schein.

I don't expect we get a fading animation implemented on the short-run for the "fallback" option TeleTAN, as the current preference is to solve the underluying root cause (here: the wrong form or QR code, repectively).

Thanks!

**Comment by not-a-feature** [comment]
> In case, there are non-10C/OEGD-Qr-Code used, would you be able to provide samples of those and the source, i.e., where they come from?

I've emailed you a sample.

> To be honest, we already are in contact with mobile emergency service teams (DRK Katastrophenschutz), those meanwhile are able to add perfectly fitting QR-Codes to their individual forms on-the-fly (we tested with labs already), so there should be no necessity to go, even when the testing was forced by health authority (Gesundheitsamt) with Ü-Schein.

They are using correct 10C/OEGD qr codes, but neither is the box checked nor the qr codes handed out to the patient. (Probably due to time reason and due to the very low usage of the CWA in a nursing home)

> I don't expect we get a fading animation implemented on the short-run for the "fallback" option TeleTAN, as the current preference is to solve the underluying root cause (here: the wrong form or QR code, respectively).

Why not both :D

> Thanks!
Glad to help

**Comment by ndegendogo** [comment]
In late October I got a test at our local test center at Fürstenfeldbruck. No paperwork, everything digital, self-registration via a website. The website registration gave me a QR code, and this code was then used as identifier towards the lab. In the whole process there was no form 10C or whatever. And the QR code was a different system, not cwa. I tried to scan it with cwa, but got only funny error messages.
Luckily my test was not positive; and luckily I was aware of the TeleTAN fallback procedure.

I have not been there since that time. No idea if they are meanwhile better integrated with cwa infrastructure.

**Comment by heinezen** [comment]
@ndegendogo Maybe we should cover these non-CWA QR Codes in the FAQ...

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@ndegendogo 
Do you still have the local test center QR code available? If yes, could you scan it with a regular QR scanner and tell us what the format is? 

According to https://update.kbv.de/ita-update/Blankoformulare/10C_OEGD/KBV_ITA_VGEX_Implementierungshinweise_10C_OEGD.pdf
the format of the QR code to be scanned into CWA is:

https://localhost/?XXXXXX-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX.
for example:
https://localhost/?3D6D08-3567F3F2-4DCF-43A3-8737-4CD1F87D6FDA

**Comment by ndegendogo** [comment]
@MikeMcC399 the number was much shorter than cwa numbers. Actually, it was not even an URL, but 'DExxxxxxxx' (DE + 8 digits).
I think it was the sample number of my swab. I was given a flyer with instructions to contact the health authority and to self-quarantine in case of a positive result, and the code, to be used at the hotline in case the result is delayed.

As a user of cwa I try to scan this number. I remember that I tried several times, but got only error messages like the light is insufficient. cwa should give better error messages, e.g. if it detects that the format does not match its expectations, it should tell the user that the number is from a different system *(and maybe this improvement is already implemented?)*

**Comment by MikeMcC399** [comment]
@ndegendogo 
Thank you very much for providing the details of a real problem case! Based on that I have submitted a new wishlist item #343.

**Comment by dsarkar** [comment]
@ndegendogo 

> Um die Labore lückenlos anzubinden und die Benachrichtigung des Testergebnisses durch die Warn-App sicherzustellen, möchten wir Sie bitten, folgende Informationen an corona-warn-app.opensource@sap.com zu senden: Datum, Arzt, Labor (falls bekannt), Mobilfunkanbieter, Schwierigkeiten beim Scan des QR-Codes etc. und die Information, ob Sie eine Einverständniserklärung zur Übertragung des Ergebnisses an die App gegeben haben. Je mehr Informationen wir erhalten, desto besser können wir diesen Prozess korrigieren und die Qualität der Corona-Warn-App weiter verbessern.

Thanks!

@GisoSchroederSAP FYI

**Comment by ndegendogo** [comment]
> möchten wir Sie bitten, folgende Informationen an corona-warn-app.opensource@sap.com zu senden

@dsarkar done - thanks for reminding!

**Comment by dsarkar** [comment]
@ndegendogo Thanks!

**Comment by dsarkar** [comment]
@ndegendogo Update: They are aware of that specific case and working on it.

**Comment by dsarkar** [comment]
new 
Internal Tracking ID: [EXPOSUREAPP-5124](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5124)
