### ISSUE TITLE
Impfstatus in der App

### ISSUE THREAD

**Issue by Sundie1** [corona-warn-app/cwa-wishlist#283]
## Feature description

Es sollte überlegt werden den Impfstatus in der App mit aufzunehmen.  Dieses kann wie bei #229  vorgeschlagen auch über ein QR scan beim impfen erfolgen. Darüber Hinaus sollte die App dann keine Warnungen mehr anzeigen und ich sollte die App auch als Nachweis zur Impfung nutzen können. 
Ziel sollte eine Verhinderung einer Zettelwirtschaft sein wie wir sie derzeit in Restaurants erlebten und von vornherein auf eine Digitale Lösung setzen. Diese sollte im Prinzip ganzheitlich sein und schon beim impfen beginnen. Dort scanne ich meinen impfcode um den Modus der App zu ändern. Gleichzeitig bekomme ich einen countdown angezeigt wann die Auffrischungsimpfung zu erfolgen hat. 
Gibt es neue Erkenntnisse zu einem Impfstoff bezüglich der Dauer der Immunisierung (zb nur 2 Jahre anstatt 4 Jahre) kann durch eine Zentrale Einstellung Personen mit diesem Impfstoff vorzeitig wieder zum nachimpfen geholt werden (Warnung in App) und ggfs gleichzeitig der corona warn App Modus wieder aktiviert werden. 

## Problem and motivation

Bin ich geimpft wird die App in der derzeitigen Form nutzlos und eigentlich müsste ich diese deinstallieren. 
Derzeit gibt es aber Überlegungen von einigen Firmen nur geimpften Personen  Zutritt zu gewähren (zb eine Fluggesellschaft). Um die Zettelwirtschaft die damit verbunden wird sollte direkt von vornherein auf eine Digitale Möglichkeit des Nachweises gesetzt werden.
Dieses könnte in der Corona App sein um hier alle Themen zum Thema Corona zu bündeln. Und ebenfalls würde so ggfs verhindert werden das geimpfte Personen die App deinstallieren. 
Umsetzung kann per QR Code scann erfolgen. 

Natürlich darf die App wenn ich Status geimpft bin mir keine Warnungen mehr anzeigen mich testen zu lassen. 

Ist ein analoger Impfnachweis (als Papierlösung) erst einmal etabliert (siehe Kontaktdaten im Restaurant) kommt man da schwer wieder von weg. Nutzen wir also die App um digitaler zu werden. 

---
Internal Tracking ID: EXPOSUREAPP-3429

**Comment by heinezen** [comment]
Hello @Sundie1 

Thank you for the suggestion. I've linked your issue in our internal Jira, so that the developers and the RKI can discuss the proposal. Since your suggestion is very similar to https://github.com/corona-warn-app/cwa-wishlist/issues/229, I will close your issue as a duplicate and link it in the other thread to keep the discussion about the feature centralized in one place. You are alsoo free to copy your comment over. We will notify everyone in the other thread when we get more feedback from the developers about the topic.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/229
