### ISSUE TITLE
Increase app usage by offering financial incentives to users

### ISSUE THREAD

**Issue by OlympianRevolution** [corona-warn-app/cwa-wishlist#291]
## Feature description

In order to rapidly increase usage there should be financial incentives for app usage. Users could be paid a sum for downloading the app as well as additional amounts for persistent usage. In my opinion the amount should be relevant, i.e. 3€ - 10€ per week or so, but the exact height of the payment would be decided elsewhere of course. This would mean that users have to opt in to this non anonymous part of the app.

## Problem and motivation

App usage is too low to have a significant impact in discovering exposures. Contact Tracing is a quadratic problem since both people have to use the app. This means that if as currently 20% of people use the app only 4% of contacts will be identified. To detect 50% of contacts 70% of the population would need to use the app (0.2 * 0.2=0.04 and 0.7 * 0.7=0.49). Thus the focus should be on increasing app usage either through legislation or additional benefits (financial rewards for app users as suggested here or other benefits)

Offering financial incentives may be more effective than ads at motivating people to download and use the app. This would also increase the apps media coverage. The Cost should be small compared to the enacted economic stimulus packages even for large financial incentives of 5-10€ per week and could partially replace some of the stimulus programs.

Obviously increasing usage would save lives and possibly decrease the duration of restrictions. 

## Is this something you're interested in working on

Yes, but I have only limited skills to do so.

----
Internal Tracking ID: EXPOSUREAPP-4468

**Comment by Ein-Tim** [comment]
Related: #150

**Comment by heinezen** [comment]
Hey @OlympianRevolution ,

Thank you for the request. The RKI and the devs will now discuss your proposal internally. For that purpose, we have created a ticket in our internal Jira (EXPOSUREAPP-4468). Once we get feedback from the devs or the RKI, we will post it here on Github.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by alanrick** [comment]
No feedback from the RKI so far but here’s a study from Nature that used a sample of 2000 people to quantify this proposal. 
[https://rdcu.be/cehx8](https://rdcu.be/cehx8)

**Comment by rolfwilms** [comment]
Instead of offering a small incentive to all, one may consider connecting the app usage with a lottery, providing substantial amounts to some. This could be more attractive to users, cause higher media attention, and easier to handle than paying out small amounts to millions of users.

Technically, it could work like this:
- Every day, the app connects to the server and provides a cryptographic hash of the SIM card's ICCID to the server (ticket claim). The server signs that ticket claim + current date and sends it back. This is the lottery ticket. The server signs only one ICCID hash per day.
- The casting of lots is done by e.g. taking the cryptographic hash of the last Bitcoin block mined the previous day. If the first n bits, n TBD, of the block hash equal the hash of the signed ICCID+current date hash, the ticket wins.
- The app can display if your ticket won.
- You claim your win by providing the ticket and your SIM card as proof. This could e.g. be handled by the state lottery.
- Benefit: Anonymous process with no pre-registration required and hard to hack

**Comment by gitbreaker222** [comment]
I appreciate this creative lottery idea and think it addresses all of those people, who don't install the app just because they don't see "What is in there for **ME**" and it would bring some positive thoughts back after one fckng year of social-distancing and wave after wave

:+1:

**Comment by MikeMcC399** [comment]
@gitbreaker222 

Maybe you'd like to add your opinion to the survey on https://umfrage.uni-wuppertal.de/index.php/765823?lang=de ?

This was posted in the [CWA blog](https://www.coronawarn.app/en/blog/2021-02-23-corona-warn-app-survey/) on Feb 23, 2021.

It seems the survey is still open for input. Feel free to pass the information on to others.

**Comment by Velligis128** [comment]
I would also suggest to incentive the upload of a positive test, e. g. with food within the usual quarintine time. This could be handle via anonymous vouchers, e. g. via sodexho or other companies.

**Comment by alanrick** [comment]
> The RKI and the devs will now discuss your proposal internally. For that purpose, we have created a ticket in our internal Jira (EXPOSUREAPP-4468). Once we get feedback from the devs or the RKI, we will post it here on Github.

Did the RKI  find time in the Last 3 months to discuss this suggestion?

While I prefer other incentives myself (e.g. guarantee of an immediate anonymous test if notification received, or allowing the anonymous venue-checkin to be used _instead_ of the paper trail) I nevertheless would like to know the RKI believes.

**Comment by heinezen** [comment]
Hello everyone,

This feature has been **declined** and will not be pursued further.

----
Corona-Warn-App Open Source Team
