### ISSUE TITLE
[Overview] Issues reg. vaccination (certificates)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#312]
**This is an overview over all open Issues regarding the vaccination (certificates)** (to keep track and avoid duplicates).
**Please note that the issues that affect other types of certificates are listed in #602.**

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| #229 | Report and track adverse side effects inside of CWA | **OPEN** | [EXPOSUREAPP-3429](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3429) |
| #300 | Include registration for vaccination | **OPEN** | [EXPOSUREAPP-3429](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3429) |
| #341 | Prevent vaccine waste by notifying vaccination volunteers | **OPEN** | [EXPOSUREAPP-3429](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3429) |
| #547 | A way for non-EU citizens, vaccinated in the home country (!=Germany) to be able to get vaccine certificates | **OPEN** | [EXPOSUREAPP-7978](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7978) |
| #574 | Enhance vaccination certificate acceptance for outside of Europe | **OPEN** | not mirrored | 
| #554 | Always show exact date when full vaccination status is reached  | **OPEN** | [EXPOSUREAPP-7979](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7979) |
| #561 | Show "some green" for status full vacccined status | **OPEN** | not mirrored |
| #570 | Schnittstelle zum Fahrzeug für digitalen Impfpass | **OPEN** | not mirrored |
| #595 | Make CoronaWarnApp more fun: Konfetti for a completed vaccination | **OPEN** | not mirrored |
| #632 | Bigger text size for vaccination date label underneath QR-Code | **OPEN** | not mirrored |
| #678 | Do not show information about vaccination certificate and just show QR Code | **OPEN** | [EXPOSUREAPP-10546](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10546) |
| #699 | CWA zur Vor- und Nachbereitung der Impfung nutzen | **OPEN** |  [EXPOSUREAPP-10779](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10779)  |
| #728 | Add "Booster #x" to CWAs detail screen of a DCC... | **OPEN** | [EXPOSUREAPP-11113](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11113) |
| #743 | Send rare or longterm symptoms to PEI | **OPEN** | [EXPOSUREAPP-11180](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11180) |

This overview was last updated on 21.02.2023 (dd.mm.yyyy).

---

Internal Tracking ID: [EXPOSUREAPP-3429](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3429)

**Comment by kathrinnos** [comment]
Hi, 
is this an appropriate place to provide additional thoughts on notifications about the vaccination process?
Here is my thought: I am in Baden-Württemberg. I would like to register for a vaccination as soon as my priority group is eligible for the vaccination - which will be some time in the future. It would be great to get the information about when my group is eligible.
In order to get this information, how about allowing me to register for a region (here: The Bundesland I am in) and send push notifications for all regions and all priority groups without needing to keep a central registry of people who want to get the vaccination? My phone will then display only those notifications to me that fit my selection (which would be Baden-Württemberg in my example).
As it seems, the different regions (Bundesländer) will use different registration mechanisms. It would really be helpful to receive the information relevant for me as soon as I am eligible. I suppose that implementing something as described above would not be very much work, would still obey data protection and privacy (I perform a setting within my app on my phone), and only requires the issuing of respective push notifications (display according to filter). The information where and how to register per region would be helpful, too. 
Thank you for considering this - best regards, Kathrin.

**Comment by Ein-Tim** [comment]
Hey @kathrinnos.
I think it would be good if you comment on #300, since this is just an overview. 

Thank you!

**Comment by kathrinnos** [comment]
Thank you, Tim, I commented it there.

**Comment by Ein-Tim** [comment]
@dsarkar 

Could you please ask around if there is still internal will to continue the Overviews? Due to changes in my working situation (see [this](https://github.com/corona-warn-app/cwa-app-ios/issues/4602#issuecomment-1408919421) comment) I'll have less time to continue updating them and would close them soon. I think that, thanks to the widely used labels in this repository, issues are very well sorted into categories and the overviews can be discontinued.

**Comment by dsarkar** [comment]
@Ein-Tim I suggest keep them open for now, we will try to maintain these overview issues.

**Comment by Ein-Tim** [comment]
@dsarkar FYI: I updated all overviews one more time today.

**Comment by Ein-Tim** [comment]
As [CWA development is ending](https://www.coronawarn.app/en/faq/results/#ramp_down), I'm discontinuing this overview.
