### ISSUE TITLE
[Overview] Issues reg. Test & Share Process

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#313]
**This is an overview over all open Issues regarding the test result process** (to keep track and avoid duplicates). 

## Test results / QR-Codes:

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| #224 | URL Scheme in QR Code | **OPEN** | [EXPOSUREAPP-5774](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5774) |
| #227 | Allow manual code entry to register COVID test (without QR scan) | **OPEN** | [EXPOSUREAPP-3415](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3415) & [EXPOSUREAPP-5095](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5095) |
| #284 | Make it as easy as possible to share positive results | **OPEN** | [EXPOSUREAPP-4680](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4680) |
| #302 | Entering QR-Code hex values manually if QR-Scan fails | **OPEN** | [EXPOSUREAPP-3415](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3415) & [EXPOSUREAPP-5095](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5095) |
| #340 | Display more information for a positive result| **OPEN** | [EXPOSUREAPP-5020](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5020) |
| #463 | Integrate CORSIGN QR Codes for positive tests | **OPEN** | not mirrored |
| #483 | In-App Approval to Receive the Corona Test Result in the CWA App | **OPEN** | not mirrored |
| #518 | Allow multiple tests to be added and always display the most current one | **OPEN** | not mirrored |
| #751 | Increase percentage of shared positive test results | **OPEN** | [EXPOSUREAPP-11240](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11240) |
| #795 | Notify User to Retrieve Test Result from Testing Site when Test Result is not available in CWA after +48hrs | **OPEN** | [EXPOSUREAPP-11925](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11925) |

## Other submission relates issues 

| Issue | Title | Status | JIRA |
| --- | --- | --- | --- |
| #398 | Function to "book" a test - Both rapid and PCR-based | **OPEN** | [EXPOSUREAPP-5888](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5888) |
| #725 | Flyer for motivating the use of the CWA from test-centers | **OPEN** | [EXPOSUREAPP-11521](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11521) |
| #818 | Bestätigung für Geburtsdatum bei Testregistrierung | **OPEN** | [EXPOSUREAPP-12596](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12596) |

**References**
- [from comment](https://github.com/corona-warn-app/cwa-app-android/issues/1551#issuecomment-753023940)
LEITFADEN ZUR IMPLEMENTIERUNG MUSTER 10C/E UND MUSTER OEGD/E 
https://update.kbv.de/ita-update/Blankoformulare/10C_OEGD/KBV_ITA_VGEX_Implementierungshinweise_10C_OEGD.pdf

This overview was last updated on 21.02.2023 (dd.mm.yyyy).

---
Internal Tracking ID: [EXPOSUREAPP-5774](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5774)

**Comment by annebeckmann** [comment]
I would like to add a process issue and solution that I did not find represented here:
It may solve the problem, that leads to currently 38% of CoronaWarnApp-Users NOT sharing their test results.
![image](https://user-images.githubusercontent.com/76115904/115945086-29f92c00-a4ba-11eb-8afc-26e013ecec6d.png)

The form 10c / OEGD of the Kassenärztliche Vereinigung does not take into consideration, that most PCR-Tests of infected pationts are carried out OUTSIDE the medical practice. This leads to a situation that consent is systematically not communicated on the form.

![image](https://user-images.githubusercontent.com/76115904/115945200-d89d6c80-a4ba-11eb-8ef2-d6022475b985.png)

Potential Solution:

![image](https://user-images.githubusercontent.com/76115904/115945227-f539a480-a4ba-11eb-9e26-a19876bd21c0.png)

If there is anything wrong with my description, I would be glad to understand this. I have written this to KBV several times, but they either don't understand me or don't seem to take it seriously. This is completely incomprehensible to me, because on average 48 people die every single day because of this.

(Among these people, there may be one or two who really don't want to give their consent, but the likelihood of people using a warning app to NOT warn other people is pretty low, isn't it?)

Any further questions? Please do not hesitate to ask.

In case, I posted this in the wrong place, please move it or bring this to the attention of people in charge with Test & Share Processes. Thank you. Anne

**Comment by ndegendogo** [comment]
@annebeckmann Thank you very much for your valuable feedback, your insights on the shortcomings of this form, and your suggestions to improve this.

> In case, I posted this in the wrong place, please move it or bring this to the attention of people in charge with Test & Share Processes. 

Indeed there is such a ticket where such information are collected. Although it is not so easy to find.

https://github.com/corona-warn-app/cwa-documentation/issues/400

You will find several comments and suspicions that this checkbox might have some impact. But I have never seen such a clear and understandable process description at the doctors that shows that it is indeed broken.

So I suggest, if it is not too much work from your side, that you post again your comment and suggestions to that ticket.

Furthermore, the developer team has published an email where they collect such feedback and act upon.

corona-warn-app.opensource@sap.com

So alternatively you could send your suggestions to that email. (Or even both, comment on that ticket and send the email)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
"Wie im ITA-Newsletter vom 14. Mai 2021 bekanntgegeben wird ITA-FTP-Updateserver (ftp://ftp.kbv.de/ita-update/) heute, am 30. Juni 2021, abgeschaltet. Sie finden seit Ende 2020 alle Dokumente, Stammdateien und die KBV-Software auf dem Update-Server der KBV unter https://update.kbv.de."

So please update the link you copied.

**Comment by Ein-Tim** [comment]
@MikeMcC399
Thank you. I'll search for the right document when I have time. 

At the moments I don't actively maintain the overviews, but I'll clean them up and update them soon.

**Comment by MikeMcC399** [comment]
https://update.kbv.de/ita-update/Blankoformulare/10C_OEGD/KBV_ITA_VGEX_Implementierungshinweise_10C_OEGD.pdf

**Comment by Ein-Tim** [comment]
As [CWA development is ending](https://www.coronawarn.app/en/faq/results/#ramp_down), I'm discontinuing this overview.
