### ISSUE TITLE
Make it easier to call the right help line number

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-wishlist#329]
In Bild, it was reported that people are having difficulties calling the right phone number for help according to a leading doctor: https://www.bild.de/news/inland/news-inland/coronavirus-ticker-aktuell-corona-warn-app-legt-gesundheitsaemter-lahm-70411946.bild.html#fromWall

>„Es sprengt alle Dimensionen, die wir je hatten“, sagte die Vorsitzende des Bundesverbandes der Ärzte im öffentlichen Gesundheitsdienst, Ute Teichert. „Die Leute kommen mit der App nicht klar und sie kommen auch nicht klar mit der Telefonnummer, die da angegeben ist.“

Find out what the usability problems are and solve them so that people don't overwhelm the local health authorities and call the central help line instead.

Internal Tracking ID: [EXPOSUREAPP-1880](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-1880)

**Comment by MikeMcC399** [comment]
I wonder if this is still a problem, because this issue hasn't been commented on for more than 6 months old.

The Request TAN screen has a button labelled "CALL".

![image](https://user-images.githubusercontent.com/66998419/104312984-a9e52280-54d7-11eb-860c-22f93e3c5885.png)

---

Does the Technical Hotline screen also need a CALL button?

three-dot overflow menu > App Information > Technical Hotline

**Comment by Ein-Tim** [comment]
I can say that there is no CALL button for the Technical Hotline under iOS

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I can say that there is no CALL button for the Technical Hotline under iOS (CWA 1.10.1)

It's good that you checked that iOS is the same as Android in this respect.

On Android if you tap on the phone number
+49 800 7540001
it brings up the Phone widget and then you just have to tap on the phone symbol to start a phone connection to the technical hotline number, however there is no explicit CALL button in the previous screen.

To make the user experience consistent for both the hotline numbers (technical and TeleTAN) the screens which show each of the respective phone numbers should have a CALL button on them.

Due to the change regarding reachability of the hotlines from outside Germany (see https://github.com/corona-warn-app/cwa-documentation/issues/501) there will need to be changes made to these screens in any case.

**Comment by Ein-Tim** [comment]
@MikeMcC399

Regarding the "Call" button, is it still there under Android? Because under iOS it isn't and if this is still not aligned I'd open a new issue for this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I believe that the information about how to call the App Hotline and the TAN Hotline is now sufficiently well displayed in the app that this is no longer an issue, and that this wishlist item should now be closed.

If anybody thinks otherwise perhaps they could contribute with information about where users are having difficulty these days.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I think so too, but my question was if there is still a "CALL" button on the "Request TAN" screen 😄.

**Comment by MikeMcC399** [comment]
Under Android the screen is called "Request TAN for PCR Test" and it includes the phone numbers for calling within Germany and from outside Germany. If you tap on either of the numbers the phone app opens to be able to dial the number by tapping the call button (phone icon).

There is no longer a Call button in the CWA Android app, however there is a call button in the phone app.

I probably misunderstood the intentions of your question, so I hope that the above helps. I don't think there is any need for additional actions.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes this helps! Thank you!

**Comment by heinezen** [comment]
@Ein-Tim @MikeMcC399 @corneliusroemer 

The dev team considers it solved, so I would close here. We can reopen if we see a significant number of confused users.

----
Corona-Warn-App Open Source Team
