### ISSUE TITLE
gamification: show number of BT contacts and compare to other users (in your area)

### ISSUE THREAD

**Issue by floetenpiet** [corona-warn-app/cwa-wishlist#332]
The major problem I had with the CWA from the very beginning was: Am I doing this pandemic right? Am I behaving properly? Do I have more or less contacts than the average person my age? There is no answer to this!

I think most of the users think they behave better than the average, therefore they grant themselves "exceptions", but 50% are wrong but unknowingly!

The App contains all the information we need: number of BT contacts, exposure time, and historical statistics. It just has to share part of this information anonymously.

I think most users would apreciate more feedback from the app whether the personal behaviour has "improved" in terms of "reducing contacts". Since this reduction seems to be the key to overcome this pandemic, we should nudge people everywhere we can to question, reflect and improve their behaviour. Not to "punish" them, but to motivate them. This way, if everyone wants to belong to the 50% behaving better than the "rest", everyone would improve.

Data privacy issues will be solvable. Or make it an optional thing, there are ways.

**Comment by Ein-Tim** [comment]
Hey @floetenpiet 👋🏻

Please take a look at #5, it seems that this is nearly the same proposal as your one.
If you think so too, please close this Issue and monitor (and if necessary follow up in) #5. 

As you also can see in #5, there is no way for Corona-Warn-App (with the current implementation) to show like the BL contacts in range, etc., since this is all done by the OS and CWA does never get in touch with the Bluetooth beacons.

**Comment by ArneDee** [comment]
Thanks for coming back to this. I understand that there are certain "restrictions" of PWA, but this is also the main design flaw of the app in my opinion: It delivers nothing but uncertainty and insecureness to the users.
"Oh: one green encounter? Where and when? Which situations can I prevent in the future to further mitigate my risks?"

The app does not answer any of those questions. From a user's perspective, this is frustrating because there is hardly any feedback to users that want to contribute to ending this pandemic. There is no "user problem" the app solves. Major fail!

That's why it continues to fail and always will fail, I suppose. A lot of money down the drain.

Best of luck!

**Comment by floetenpiet** [comment]
Technically not feasable

**Comment by Ein-Tim** [comment]
Version 1.12 will contain some statistics (https://github.com/corona-warn-app/cwa-app-ios/pull/1807). 🎉
