### ISSUE TITLE
[Android][Solved][HowTo] OS Settings: Avoid unnecessary notifications 

### ISSUE THREAD

**Issue by legalbit** [corona-warn-app/cwa-wishlist#35]
As mentioned [here](https://twitter.com/oliverkremer/status/1275599642164633601?s=19), the users of the (Android) app are notified that everything is _fine_. 

This is an unnecessary hint, especially since there is only one option in the settings to be notified about a _changed risk_.

At least another icon (currently a **red** virus 😮) should appear.  Or do you want to scare the users ;)

Stay healthy!

------
Internal Tracking ID: EXPOSUREAPP-2144

**Comment by dsarkar** [comment]
Hi @niklasmohrin, @legalbit,

is this still an issue with CWA version 1.7.1 ?

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by legalbit** [comment]
@dsarkar 

No, I haven't received *any* notifications from the app for a long time, although the notifications are activated.

**Comment by niklasmohrin** [comment]
Hey @dsarkar I hope you are all well. I tested my workflow again on version 1.7.1.

Unless I am really quick, my notification tray closes before I am done switching everything (wifi off, gps on, bluetooth on, mobile data on).

I also noticed something else: When I have bluetooth and gps on and I want to turn both off, I get one notification that disappears right away (thus closing the tray), but after it is closed, there is another notification (because now both are turned off). I then have to swipe down the tray again, only to dismiss the notification.

Correct me if I'm wrong, but I think there is no setting to turn this off. Although this might not apply to everyone, I personally know that I turn of the app services when turning off bluetooth and gps and would like an option to at least disable the final notification (when both are turned off).

Thank you!

**Comment by dsarkar** [comment]
Hi @niklasmohrin,

Just to clarify

- With 'GPS' you mean 'Localization services'?
- What is the second (last) notification saying?

Thanks.  Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by niklasmohrin** [comment]
@dsarkar Exactly. The specific notification I am talking about is this one:
![image](https://user-images.githubusercontent.com/47574893/101368940-071e0080-38a8-11eb-842d-835c9da3f6b8.png)

It appears once right after I switch off either one of bluetooth or localization services and a second time after the other one is turned off.

**Comment by MikeMcC399** [comment]
@niklasmohrin 
The notification you showed is provided by the Google Exposure Notifications System. It is not controlled by the Corona-Warn-App.

I'm seeing the message changing, depending on whether only Bluetooth is disabled, or Location (Standort) is disabled or both.

Here are the three different messages:
- Wenn du diese Funktion verwenden möchtest. aktiviere Bluetooth
- Wenn du diese Funktion verwenden möchtest, aktiviere die Standortermittlung
- Aktiviere Bluetooth und die Standortermittlung, wenn du diese Funktion verwenden möchtest

You can disable these notifications in Android, but I would think twice about doing this, because you might miss an important notification. There is only one notification to dismiss when you switch off Bluetooth and Location, because the one notification is replaced by the second.

For German UI and Android 10:
Einstellungen > Apps
Google Play-Dienste
Benachrichtigungen, dann unter "andere"
COVID-19 Benachrichtigungen ausschalten

Like I said, I would not recommend anybody doing this!

**Comment by niklasmohrin** [comment]
@MikeMcC399 Thank you for the explanation! I could have spotted that myself, my bad.

I am going to research whether I can file a request to the Google service (although I don't expect a big success with that), but my request here should be done then :+1:

Thank you all for your work!

**Comment by dsarkar** [comment]
Hi @niklasmohrin,  @legalbit,

With @MikeMcC399's detailed solution https://github.com/corona-warn-app/cwa-wishlist/issues/35#issuecomment-740021048, we suggest that we can consider this issue as solved. We keep it open for better visibility. Many thanks for all the contributions.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Has the implementation changed in the meantime or is the default still that there are these notifications?

**Comment by Ein-Tim** [comment]
@MikeMcC399 Just to clarify, because I'm in discussion with a Twitter user about this, doing what you've described in https://github.com/corona-warn-app/cwa-wishlist/issues/35#issuecomment-740021048 does **not** influence push notifications from CWA itself, right? So the user will still get notifications if he had a high risk encounter.

**Comment by Eichi** [comment]
Oh, thank you very much for this great communication. I'm curious about how to get further push notifications from the app even if it is disabled within system notification settings from Android because I don't need bluetooth and geolocation at home (for energy saving) but want to be notified as soon as possible when I got a high risk encounter outside.
My thought was it would be much more understandable if the app has settings for push notifications generally (like the one mentioned above) and additionally a setting for high risk contact.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Just to clarify, because I'm in discussion with a Twitter user about this, doing what you've described in #35 (comment) does not influence push notifications from CWA itself, right? So the user will still get notifications if he had a high risk encounter.

I can't imagine that the two are linked. I don't have the possibility to test it though.

**Comment by larswmh** [comment]
Closing this issue as it was set to obsolete in its related internal ticket. Abovementioned visibility might have been a good reason  to keep this issue opened back then, but considering that we have hundreds of open wishlist items now I can't agree with this anymore. Apart from that, even if closed, this GitHub issue will still be visible.
