### ISSUE TITLE
Enable GitHub discussion for all CWA repositories

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#360]
## Current Implementation
GitHub discussion is only enabled for the https://github.com/corona-warn-app/cwa-server repository.

## Suggested Enhancement
Enable GitHub discussion on all CWA repositories.

## Expected Benefits
Give the community another space for discussion and feedback.
Questions (which are not relevant long term) could be asked and answered there to keep the issue section clean.

**Comment by heinezen** [comment]
Does that offer a significant advantage over answering question in issues? Afaik, Discussions can't be added too project boards yet which makes monitoring and managing them more difficult for us community managers.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
I would go the opposite way and disable the discussion board on the server repo. That discussion board has never been used and removing it would make it consistent with the other repos.

We already have quite a number of issue lists to look at and it is often not easy to remember in which repo a topic was discussed because the lists often overlap. Doubling the number of lists, by adding a parallel set of discussion boards, would make it even harder to keep topics together and to monitor them.

Just using issues is the best way to use GitHub under the circumstances. We don't have a fully blown ITIL-aligned help desk system to work with which separates incidents from problems, etc., so I would keep it the way it is and not create new discussion boards.

**Comment by Ein-Tim** [comment]
Thanks for your input @MikeMcC399 & @heinezen.

I opened this issue since I thought that we could use the discussion feature for long-term visible issues (like https://github.com/corona-warn-app/cwa-app-ios/issues/1675) or questions (which already were answered) to keep the issue section a bit more clean.

Don't get me wrong, I would stay with the current solution to have the main "work" going on in the issue section, discussion could be more used like a space for the community, where mainly community members are active. 
This should definitely not be used to 
a) report issues or
b) ask questions which should be answered by the devs.

It could be a good place for new interested people which have questions which can be quickly and only answered by the community (I'm thinking mainly about the documentation repo here). 

But I also understand your concerns that this will make it harder to track and keep everything managed. 

I will leave this issue open for a bit and think about this again. 
I'm happy to hear your input & opinion regarding this! 🙂

**Comment by heinezen** [comment]
@Ein-Tim I think we would need a specific use case to make activating Discussions worth it. Even if this is a feature mainly intended for community members, we are still obligated to monitor the discussion. Issues are more managable currently because a lot of work is handled by the cwa-bot. 

Q&A features in Github Discussions are nice, but I think the questions which are quickly answered should rather belong in the FAQ. But you're right that it could be a starting point for new people. 

There is also the risk that it would split larger discussion topics between Github Issues and Github Discussion which we would want to avoid. We cannot move single comments, but only link them. Linking relevant comments back and forth between topics would not be that great.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@heinezen 

>Q&A features in Github Discussions are nice, but I think the questions which are quickly answered should rather belong in the FAQ. But you're right that it could be a starting point for new people.

With questions which can be quickly answered I meant more like thinks who are relevant for people who f.e want to build the app via an emulator but they have a question, etc.


But I see that this does, at the moment, not bring any big improvement, rather more work.

I'll close this issue for now, maybe we'll see project support for Discussions soon, IIUC this is the main point why you don't want to activate it (at the moment).

Thanks for your answers.
