### ISSUE TITLE
Integration von positiven PoC Antigen-Schnelltestergebnissen

### ISSUE THREAD

**Issue by riedborn** [corona-warn-app/cwa-wishlist#412]
Zur schnelleren Warnungen der Kontaktpersonen ist die Integration positiver PoC-Schnelltests überfällig.
Nach Vorliegen eines negativen PCR-Tests sollte eine Entwarnung veranlasst werden.
Alles was die bezüglich Datenschutz unsichere Luca-App anbietet sollte integriert werden.

---
Internal Tracking ID: EXPOSUREAPP-5469

**Comment by Ein-Tim** [comment]
Related Issues:

#371 
#374 

---

> Alles was die [...] Luca-App anbietet sollte integriert werden.

A venue registration feature will be included in the next release, version 2.0. 
See this overview for more information: #338.
Documentation reg. the even registration can be found here: https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md

**Comment by Ein-Tim** [comment]
There's now a blog post reg this:https://www.coronawarn.app/de/blog/2021-03-31-corona-warn-app-test-integration/.

**Comment by dsarkar** [comment]
@riedborn Thank you for your proposal. This feature will be implemented according to the mentioned https://github.com/corona-warn-app/cwa-wishlist/issues/412#issuecomment-811467101 the blog post. 

---
Internal Tracking ID: EXPOSUREAPP-5469
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
See the blog post https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/ announcing "Project team integrates rapid COVID-19 tests into Corona-Warn-App version 2.1"

or the German version https://www.coronawarn.app/de/blog/2021-05-02-corona-warn-app-version-2-1/ 

"Nach Vorliegen eines negativen PCR-Tests sollte eine Entwarnung veranlasst werden." - this request is however not fulfilled by the new version.

"In Fall eines positiven Schnelltest-Ergebnisses sollten Nutzer*innen außerdem umgehend einen PCR-Test machen, um das Ergebnis zu bestätigen oder zu widerlegen. Bei einem positiven PCR-Test, sollten Nutzer*innen auch dieses Testergebnis teilen. So können sie Kontaktpersonen warnen, denen sie möglicherweise seit Teilen des Schnelltest-Ergebnisses bis zum Teilen des PCR-Test-Ergebnisses begegnet sind. Sollte der PCR-Test negativ sein, haben sie aber nicht die Möglichkeit, ihren positiven Schnelltest und die Warnung zurückzuziehen."

**Comment by riedborn** [comment]
I'd like to partecipate in the integration of the result of a rapid test into the CWA. I'm as owner of a retail pharmacy a member of Deutscher Apothekerverband. It is not more listed at the blog.
What to do?

Wolfgang Weiler 

Am 2. Mai 2021 15:52:02 MESZ schrieb Mike McCready ***@***.***>:
>See the blog post
>https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/
>announcing "Project team integrates rapid COVID-19 tests into
>Corona-Warn-App version 2.1">
>>
>or the German version
>https://www.coronawarn.app/de/blog/2021-05-02-corona-warn-app-version-2-1/
>>
>>
>"Nach Vorliegen eines negativen PCR-Tests sollte eine Entwarnung
>veranlasst werden." - this request is however not fulfilled by the new
>version.>
>>
>"In Fall eines positiven Schnelltest-Ergebnisses sollten Nutzer*innen
>außerdem umgehend einen PCR-Test machen, um das Ergebnis zu bestätigen
>oder zu widerlegen. Bei einem positiven PCR-Test, sollten Nutzer*innen
>auch dieses Testergebnis teilen. So können sie Kontaktpersonen warnen,
>denen sie möglicherweise seit Teilen des Schnelltest-Ergebnisses bis
>zum Teilen des PCR-Test-Ergebnisses begegnet sind. Sollte der PCR-Test
>negativ sein, haben sie aber nicht die Möglichkeit, ihren positiven
>Schnelltest und die Warnung zurückzuziehen.">
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/corona-warn-app/cwa-wishlist/issues/412#issuecomment-830812947

-- 
Diese Nachricht wurde der Flaschenpost übergeben.

**Comment by MikeMcC399** [comment]
Hi @riedborn / Wolfgang Weiler

You are right that the list has changed.

The [blog post today](https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/) it says:

"Eight partners are participating in the launch of the rapid test integration, including the German Federal Chancellery, the Bavarian Red Cross, dm-drogerie markt, Doctorbox, EcoCare the healthcare brand of Ecolog Deutschland GmbH (with Lidl among others), Huber Health Care, the Saarland Ministry of Education and Culture and testbuchen.de/No-Q." 

"Since the announcement of the rapid test integration at the end of March, the project team has received 125 requests from test centers and the retail sector, among others, that are interested in participating in the integration."

whereas in the [earlier blog post](https://www.coronawarn.app/en/blog/2021-03-31-corona-warn-app-test-integration/) it said:

"In the first phase, the following partners want to participate in the implementation of the rapid test function in the Corona-Warn-App: BUDNI, Deutscher Apothekerverband (DAV), dm-drogerie markt, DOCTORBOX, GALERIA Karstadt Kaufhof. Others are to follow. Companies that are interested in participating can contact the development partners SAP and Telekom via corona-warn-app.opensource@sap.com"

So maybe the Open Source Team can throw some light on the specific status of the "Deutscher Apothekerverband (DAV)"? Delayed? Withdrawn? Planned?

**Comment by Ein-Tim** [comment]
Can this issue be closed? 

See https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/

**Comment by riedborn** [comment]
Yes
-------- Ursprüngliche Nachricht --------Von: Tim ***@***.***> Datum: 24.08.21  19:13  (GMT+01:00) An: corona-warn-app/cwa-wishlist ***@***.***> Cc: riedborn ***@***.***>, Mention ***@***.***> Betreff: Re: [corona-warn-app/cwa-wishlist] Integration von positiven PoC Antigen-Schnelltestergebnissen (#412) 
Can this issue be closed?
See https://www.coronawarn.app/en/blog/2021-05-02-corona-warn-app-version-2-1/

**Comment by Ein-Tim** [comment]
@dsarkar @larswmh The author of this issue confirmed that it can be closed. 

Can you close it, please?
