### ISSUE TITLE
Enable multiple QR code scanning for the same application/device OR add warning text

### ISSUE THREAD

**Issue by inakuhn** [corona-warn-app/cwa-wishlist#426]
## Feature description
There are different features that can be implemented here:

- Text warming You cannot re-scan the Qr code again
-  Allows multiple Qr code scan for the same device/ID

## Problem and motivation
Since the result does not change in the lab view, there is no LastUpdate date, etc. 
After a while I assume something went wrong with my connection, so I delete the test and try to scan again.
Now I can not see my results.
## Is this something you're interested in working on

Yes

**Comment by MikeMcC399** [comment]
@inakuhn 

Normally the app will warn you that the test can only be scanned once. If that message did not appear, that would be a bug.

![The test can only be scanned once](https://user-images.githubusercontent.com/66998419/113115861-27821a00-920d-11eb-8fdf-5db487c7f0df.jpg)

You can read the reason for the restriction, of only being able to scan in the QR code once, in the [Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) in 
"6. Why is your data processed?
b. Retrieving a test result":

"Scanning the QR code

In order to retrieve your test result via the app, you will need to scan the QR code using your smartphone’s camera. The QR code contains a code number that is read during scanning and is assigned to your test. After reading the code number, the app ‘hashes’ it. This means that the app performs a certain mathematical procedure in order to convert the code number in
such a way that it can no longer be identified. However, it is still possible to clearly assign the hashed code number to your test result. As soon as your smartphone is connected to the internet, the app will transmit the hashed code number to the server system. The server system then provides a digital access key (a so-called token), which is stored in the app. The token is
linked to the hashed code number in the server system. The app now deletes the code number that has been hashed on your smartphone and keeps only the token. **Once the QR code has been used in this way, it becomes invalid and can no longer be used by anyone. This ensures that no other users can use your QR code to retrieve your test result.**

**Comment by Flobster1804** [comment]
No matter how you feel about the need for this complicated privacy - there is problem with the user experience here. No clue if this is a new behavior, but today I wanted to scan a test. I deleted my old test, and after clicking a on a few item (allowing information sharing etc.) apparently the QR scan activated itself. I was just holding the phone over the table and apparently the QR code was scanned instantly and the app directly notified me no test result was available. As I did not get a "success" information about successfully scanning the new test I thought this was an error. I deleted the test thinking the old test was still active. Now I cannot scan the new test again. 
So either you should
1) be able to scan test again
2) show more clearly that a new test was successfully scanned and show which test (date of the test) is currently active when you are deleting it!

**Comment by Ein-Tim** [comment]
> be able to scan test again

I could only imagine a solution where a never changing ID of the device is transferred to the server with the first scan of a QR-Code. Then the server knows which QR-Code belongs to which device and thus could allow more than one scan on the same device. But this would obviously be a hard privacy breach and **I am strongly against something like this!**

> show more clearly that a new test was successfully scanned and show which test (date of the test) is currently active when you are deleting it!

The app should show you a screen when (date) you added the QR-Code. I think the screen after scanning a QR-Code is clear, since you just aren't able to scan a QR-Code twice, it's always a new test.
If you have 5 unscanned CWA QR-Codes laying around at your desk and you just open the QR-Code scanner of CWA, this could get, I agree, a bit complicated.

**Comment by MikeMcC399** [comment]
@Flobster1804 
I agree that only being able to scan a test once is a major restriction.

I like your idea 
> and show which test (date of the test) is currently active when you are deleting it!

Although this information is available on the screen where you select delete, I think it would be a good enhancement to also display the registration date in the message "The test can only be scanned once".

The screenshots of the current version are on https://www.coronawarn.app/en/screenshots/. For instance the relevant Android English screen is https://www.coronawarn.app/assets/img/screenshots/en/android/SubmissionTestResultPendingFragment.png which shows the state immediately after a QR code has been scanned.

**Comment by Flobster1804** [comment]
I am just a regular user not a programmer nor an activist - therefore I cannot judge if anything is a "hard privacy breach". I can only report on the user experience and suggest remedies to improve this.

If scanning a test twice is impossible it should be prevented to delete it by accident. I believe very few normal user know you can only scan a test once and of those who know even less know or understand why. 

From the screenshots (I look at iOS) I see on the home screen no information which test is currently active. 

Additionally I experienced a strange behavior with the old test. Even though my last test was >1 month old I got the error message "test result not available". This led to my error of deleting the new test. Because after my accidental scan of the new test the error message was the same as with a 45 days old test. 

Therefore I would suggest:
- Show last test date on the home screen
- If a test is >21 days old have a different error message when clicking on the result or delete the test automatically (I see the screen of Andriod has this, but at least in my iOS app this was not the case)
- As above: have a success message after a new test is scanned
- As above: show which test you are deleting

**Comment by Ein-Tim** [comment]
@Flobster1804 

I'm also not a developer so just to clarify: I also cannot judge if this would be a "hard privacy breach", but I can only say that this would be against the spirit of the project and everything what has been implemented so far (maybe besides of the data donation feature - which is voluntarily and the upcoming feature of the log upload - which is voluntarily too). 
So what could be done is to implement this in a voluntary way - an opt in to allow that a identifiable is transferred to the CWA server. 

But I agree that the adding of a test result could be improved, as described by you above.

**Comment by inakuhn** [comment]
I probably didn't see the alert dialogue or totally ignored it because it is a long text. 
I will close the ticket.

**Comment by dsarkar** [comment]
@inakuhn Thanks for contributing here!


---
Corona-Warn-App Open Source Team
