### ISSUE TITLE
Integration of the SafeVac 2.0 App

### ISSUE THREAD

**Issue by beneeeeeee** [corona-warn-app/cwa-wishlist#467]
**## Feature description**
Users can also use all the functions of the SafeVac 2.0 app (reporting of side effects through regular queries) in the CWA after vaccinations have been carried out. 

More details on the SafeVac 2.0 App of PEI: https://www.pei.de/DE/newsroom/hp-meldungen/2020/201222-safevac-app-smartphone-befragung-vertraeglichkeit-covid-19-impfstoffe.html

**## Problem and motivation**
Many users are not familiar with the PEI's SafeVac 2.0 app. The integration of the app into the CWA would make the application better known and provide more users with more data on vaccination and the side effects that occur.

With a correspondingly large amount of data on vaccination, it might be possible to assign/discover side effects more quickly.

**## Is this something you're interested in working on?**
Yes, but I have only limited skills to do so.

**Comment by MikeMcC399** [comment]
@beneeeeeee 

I think that your suggestion is already covered in https://github.com/corona-warn-app/cwa-wishlist/issues/229 where SafeVac is mentioned.

**Comment by Ein-Tim** [comment]
@beneeeeeee 

Please close this issue if you agree with @MikeMcC399. 

Thank you!

**Comment by MikeMcC399** [comment]
BTW: You can install SafeVac any time you like, but in order to use it, you have to enter your vaccination in the app within 48 hours of being vaccinated. Also you have to use the same phone for the first and second vaccinations, and for the follow up health check after six months and one year (paraphrased from "About the App").

The app doesn't report back directly to the user about the statistics. It is only used to collect the data. The results will flow into better medical and scientific understanding. So, participating is more for the good of society in general.
