### ISSUE TITLE
Obtain (daily) static QR Codes via API

### ISSUE THREAD

**Issue by JWandscheer** [corona-warn-app/cwa-wishlist#471]
## Current Implementation
At the moment, the only way to generate a QR Code is to do it inside the CWA, this is not very comfortable for businesses. Although, its only possible to share a printable pdf of the QR Code, but not an Image (for example with just the Code, in 16:9 Format for Screens etc.).

## Suggested Enhancement
It would be nice to receive a QR code via REST API which, for example, returns a new code with every request (public, anonymous version without API key, with code- and event information submitted in the request) or to enable a login procedure for companies and locations with API keys so that the API automatically renews the QR code after 24 hours.
Technically, this could be a partial overlap with #399. 

## Expected Benefits
This would make it possible to automatically display the code especially in digital signage systems and on POS, without employees having to create a new code by themselves on the phone every day, print it out several times if necessary or convert it to an image, adjust the format to 16:9, etc. - This saves time and provides more security. I am not sure whether every location actually follows the recommendation and generates a new code every day.

**Comment by thomasaugsten** [comment]
There is no API needed. QR-Code can be generated locally. An API is also not recommended because this API can generate an internally event list. This means everybody can generate an QR-Code for displays or in batch processing

Here you can finde the structure and example
https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md#qr-code-structure
