### ISSUE TITLE
[Check-in] Allow event owners to warn CWA-users from infected non CWA-Users and vice versa

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-wishlist#486]
## Current Implementation

The CWA-checkin and the paper-lists are two incompatible systems.

## Suggested Enhancement

Let the event owner warn CWA users about an infectious person, who used the paper list and warn persons, who used the paper list about an infectious CWA user.

## Expected Benefits

Compatibility between CWA and paper list and maybe the official go for the checkin feature as a possibility.

## Compatibility Table

Thanks @floscher for creating this table.

 <table>
 
 <tr><th colspan=2 rowspan=2></th><th colspan="3">A person who checked in using … at the event tests positive and tries to notify others</th></tr>
 
 <tr><th>CWA</th><th>third-party QR code</th><th>a paper list</th></tr>

 <tr><th rowspan="3">A person using … attends an event can be notified</th><th>CWA</th><td>:heavy_check_mark:  direct notification</td><td>?</td><td>:x: no warning can be issued in CWA</td></tr>
 
 <tr><th>third-party QR code</th><td colspan="3">:heavy_check_mark: The Gesundheitsamt can ask the location to share contact data collected in the third-party app with them, so those people can be contacted</td></tr>
 
 <tr><th>a paper list</th><td colspan="3">:heavy_check_mark: The Gesundheitsamt can ask the location to give them the paper lists, so the Gesundheitsamt can contact the affected people.</td></tr>

 </table>

### Concept 1
The host is forced to keep the event codes for 14 days, and in case of an infection of a non-CWA-User transmit the codes to the health authorities, which can add the infection via an web- or app-interface.

## [Concepts] Warning non-CWA-Users about infected CWA-Users
The use case for this is not that big like the other, but if the host knows, that there was an infected person, and he knows the time, he can inform the staff (e.g. in a restaurant a staff member sometimes works in contact with customers and sometimes not, but checking in and out every time is not possible) before the health authorities can do.
### Concept 1
The host has a "super user" for the event created by him, and if there's a guid published he create, the CWA shows the start- and the endtime the infected user was checked in.

----
Internal Tracking-ID: [EXPOSUREAPP-6749](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6749)
Internal Tracking ID: [EXPOSUREAPP-8356](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8356)

----
#### Android:
- Story: https://github.com/corona-warn-app/cwa-app-android/pull/3916
- Info Screen: https://github.com/corona-warn-app/cwa-app-android/pull/3917
- Submission: https://github.com/corona-warn-app/cwa-app-android/pull/3921
- Error handling: https://github.com/corona-warn-app/cwa-app-android/pull/3952
#### iOS:
- Preparation: https://github.com/corona-warn-app/cwa-app-ios/pull/3364
- Unit Tests: https://github.com/corona-warn-app/cwa-app-ios/pull/3375
- Request: https://github.com/corona-warn-app/cwa-app-ios/pull/3387
- UI Tests: https://github.com/corona-warn-app/cwa-app-ios/pull/3392

**Comment by fynngodau** [comment]
A similar idea was discussed on slack recently ([covidapps slack link](https://covidapps.slack.com/archives/C0194ML0MLN/p1619008732014500)).

The idea was that an event organizer should be able to opt in to always receive warnings about events they created, such that they can notify other guests in case of an infection. This could be a per-event setting.

**Comment by heinezen** [comment]
Hey @jucktnich ,

Thank you for the request. We have forwarded the feedback to the developers. The development team and the RKI will now decide if and how this would be implemented. Tracking ID: [EXPOSUREAPP-6749](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6749)

----
Corona-Warn-App Open Source Team

**Comment by floscher** [comment]
Yes, I think it's very important to allow CWA users to warn non-CWA users and the other way around. Especially when there are now ambitions to allow the CWA to be used without also giving your contact data to the location: [„Datenschutzkonferenz: Länder sollen Check-in mit Corona-Warn-App erlauben“ in netzpolitik.org](https://netzpolitik.org/2021/datenschutzkonferenz-laender-sollen-check-in-mit-corona-warn-app-erlauben/)

There are three groups of people that in my opinion should be able to warn any other people from the other groups:
* users that check in with the CoronaWarnApp
* users that check in with a CWA-compatible third party app as described in [`event_registration.md`](https://github.com/corona-warn-app/cwa-documentation/blob/d7525f18dd7bde76cce83fe8976d89d52ebfcd04/event_registration.md#qr-code-compatibility-with-other-contract-tracing-apps-in-germany)
* users that fill out a paper form that the venue owner keeps


I've put together a table showing my current understanding of who can notify whom at the moment. Feel free to correct me, when I got something wrong:
<table>
<tr><th colspan=2 rowspan=2></th><th colspan="3">A person who checked in using … at the event tests positive and tries to notify others</th></tr>
<tr><th>CWA</th><th>third-party QR code</th><th>a paper list</th></tr>
<tr><th rowspan="3">A user using … attends an event can be notified</th><th>CWA</th><td>:heavy_check_mark:  direct notification</td><td>?</td><td>:x: no warning can be issued in CWA</td></tr>
<tr><th>third-party QR code</th><td colspan="3">:heavy_check_mark: The Gesundheitsamt can ask the location to share contact data collected in the third-party app with them, so those people can be contacted</td></tr>
<tr><th>a paper list</th><td colspan="3">:heavy_check_mark: The Gesundheitsamt can ask the location to give them the paper lists, so the Gesundheitsamt can contact the affected people.</td></tr>
</table>

As far as I understand it, the users of paper lists and third-party apps that collect contact data can always be notified, as soon as the Gesundheitsamt is notified that a person who tested positive attended a certain event. They would contact the location and ask them for the contact data, so they can call the other attendees.

The CoronaWarnApp users seem to be at a disadvantage, because they only get notified by other CWA users. That notification is very quick, but CWA usage is still relatively low at the moment (about 20%).
I'm not sure about the third-party apps, if those can warn CWA users. The specification says, the third-party apps should not process the CWA-data part of the QR code, so I assume they won't be able to notify CWA users.
And paper list users can't notify CWA users, because the venue or the Gesundheitsamt can't trigger a notification in the CWA system for people who did not check in using the CWA.

**Comment by jucktnich** [comment]
@floscher Thanks for creating this table. I've added it to the original proposal.

**Comment by di-sc** [comment]
May be it is not a good idea to stress the health authority and/or the venue with additional effort. The guest lists are often not used at all by the health authority.
Wouldn't it be possible to optionally check-in a virtual group user to the event for which the venue owner prints out QR-Codes and gives each visitor who manually checks-in a small printout (e.g. for a wallet).
In case the visitor who manually checked-in is tested at the testing center he will leave all QR-codes there and if the result is positive the testing center will initiate the notifications. Optionally the testing center makes copies to give them to the user for a later test.

There is a risk that the QR-Codes are copied and distributed or made public through the internet. But this is similar to the risk that already exists by copying the Check-In QR-Code.

Now only these additional QR-Codes have to be printed out and there is some more effort at the testing centers or labs.
Effort is taken away from the health authority.

**Comment by dsarkar** [comment]
@floscher et al. I updated the internal ticket. Thanks.

---
Corona-Warn-App Open Source Team

**Comment by jucktnich** [comment]
@di-sc The normal qr-codes should get "invalid" (not really but you can't abuse them), wich you can't do with printed out qr-codes for later check-in.

**Comment by di-sc** [comment]
@jucktnich The QR code should represent a virtual user which is checked in in the same way as others who checked-in by phone. He is already checked in, e.g. like the fake check-ins mentioned in [Event Registration Specification](https://github.com/corona-warn-app/cwa-documentation/blob/master/event_registration.md), not later. Because this virtual user does not have a phone he is represented by a QR-Code or if not possible by something else, call it a "ticket". This "ticket" should become invalid after 14 days when also all other Check-Ins become invalid (expiry time should be printed onto the code printout). After expiry time it should not be possible (and does not make sense at all, because also the event and all other Check-Ins became invalid) to send a warning message at the testing center with that code.

**Comment by jucktnich** [comment]
@di-sc This does reduce the possibility of abuse, but it's further possible to distribute codes. Ps.: How should such a user get checked out?

**Comment by jucktnich** [comment]
@di-sc I think, that your system does also need a new server, right?

**Comment by di-sc** [comment]
@jucktnich I think the risk of abuse is the same as for the venue check-in code itself.
But your are right. I missed the point that the app also registers the check-in start and end time. This isn't available if you only have a sheet with the "ticket" or it has to be added manually by the user and later entered at the testing center.
Maybe then the effort isn't worth it.
Anyway it is only an idea and not a perfect concept.
What you need is
- an option to create an additional "ticket" when creating the event QR-Code and printing it out n-times. By creating it, it is automatically checked-in.
- A service or web-application to scan this "ticket" at the testing center (or somewhere else, e.g. the lab) for notifying the contacts about the positive test results.

**Comment by jucktnich** [comment]
@di-sc First: The risk of abuse is much higher, cause you have 14 days for abuse, not under 1 day.
Second: How can you inform the users checked in via this codes, without the app.

**Comment by di-sc** [comment]
@jucktnich The service that is used at the testing center has to convert the "ticket" into a digital "key" and notifies the contacts in the same way as the app does.

**Comment by jucktnich** [comment]
@di-sc Yeah, if it does relate to my first point, if you check into a venue via the code at the entry, you could take a picture from it, and distribute it. At f.e. midnight, the venue owner changes the qr code and it is no abuse potential from this point on. This means you have at maximum on day. If you use the printed code instead, it takes 14 days for the code to expire. Much more time.

**Comment by di-sc** [comment]
@jucktnich That's right, yes.
Maybe the risk isn't worth it together with the check-in and check-out time problem.
But I also think that a solution that puts more load onto the health authority and requires the venue owner to later registers positive tested persons isn't worth it and would not be accepted by the health authority and venue owners.

**Comment by floscher** [comment]
@di-sc @jucktnich Also, malicious people could then collect all the printout codes of all their friends and bring them to the testing center, even if the person being tested wasn't there.

I think a better solution would be to instruct venue owners to store all the QR codes that they displayed in the last 14 days together with the paper lists. And when the contact tracers would ask for the paper lists, they also get the QR codes from the venue owner. These contact tracers would then need a special permission to create check-ins after the fact and flag those as tested positive.

This would also ensure that venues without any positive cases ever would not have to deal with overhead.

**Comment by jucktnich** [comment]
@floscher Yeah, that's the way I prefer.
@di-sc Thx for contributing

**Comment by di-sc** [comment]
@floscher Good idea!
The location-QR-code creation tool could have an option to create a visitor list with additional QR codes.
This solves both problems. The lists already have the check-in and check-out times and the lists cannot be misuesed.
Only then the health authority has to notify the users but this seems to be acceptable.
Great!

**Comment by floscher** [comment]
@di-sc I'm not really following what the additional QR codes would do. The normal QR codes that are already generated should have all the information that the contact tracers would need.

They could enter the QR code into the CWA system together with the start and end time that the person reported who tested positive. And this would create a check-in at that time in the past and mark it as positive.

**Comment by di-sc** [comment]
@floscher Yes, you are right. Maybe it is not needed anymore in that case.

**Comment by floscher** [comment]
@vaubaehn yes, both issues are practically the same. I like your description of the possible solution in your issue, it goes into more detail than my broad outline above.

That should be the way to go.

**Comment by vaubaehn** [comment]
@floscher 
I was misled by the title of the issue here, that shifts the focus for warnings to the host, and I didn't get the point right from the end of your discussion.
I edited the OP of #505 accordingly and how that's fine with you?

**Comment by di-sc** [comment]
@vaubaehn
I like your description in #505. It is precise the summary of the discussion here.
But as mentioned also in [Anhörung Bundestag - Clustererkennung, May 5th ](https://www.bundestag.de/dokumente/textarchiv/2021/kw18-pa-digitale-agenda-cluster-838094) only few circumstances exist, where the health authority will use contact lists of event at all. So I have some doubts that the health authority would use this feature. My main idea was to take load from the health authority and also from the venues but my idea is practically not feasible.
So I would recommend to implement #505, good work!

**Comment by dsarkar** [comment]
@vaubaehn Your issue is tracked in the same internal ticket. 

Dear all, This story is considered of high priority internally (Disclaimer: At this stage that doesn't mean it will/can be implemented). 


---
Corona-Warn-App Open Source Team

**Comment by jucktnich** [comment]
What's the current state of the project? Is the idea to use the existing verification portal and build a little extension to add the IDs and time of the event and upload it than?

**Comment by heinezen** [comment]
@jucktnich 

Same status as before still: https://github.com/corona-warn-app/cwa-wishlist/issues/486#issuecomment-835732699

> Dear all, This story is considered of high priority internally (Disclaimer: At this stage that doesn't mean it will/can be implemented).

----
Corona-Warn-App Open Source Team

**Comment by jucktnich** [comment]
Any updates here?

**Comment by dsarkar** [comment]
New ticket Internal Tracking ID: [EXPOSUREAPP-8356](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8356).

There is a big chance we might see this being implemented in one of the next releases, however, currently NOT planned for release 2.6 though.

**Comment by ndegendogo** [comment]
@dsarkar thanks for keeping us tuned 😁👍

**Comment by jucktnich** [comment]
@dsarkar may I ask you to add the concept you plan to use to the original post? Or is it the concept which is posted there?

**Comment by dsarkar** [comment]
The story says pretty much the same as your title ;-), i.e., that an organizer should be able to warn CWA users if a positively tested non-CWA-user attended his event, so that CWA users get warned.

I will try to get more information about the exact mechanism.

**Comment by thomasaugsten** [comment]
The organizer or the local health authority can warn for a specific timeframe and location with a specific TAN provided by the local health authority.

**Comment by viisauksena** [comment]
may i ask , what is the actual timeframe for implementing - or alternative solution is , by today
got a bit confused by all the notes and shifting here

**Comment by jucktnich** [comment]
This is planned for 2.9 and it takes about 15 to 20 days to release the next minor version of the app, so I guess it'll take 30 to 40 days.

**Comment by Ein-Tim** [comment]
Work on this has just begun: https://github.com/corona-warn-app/cwa-app-android/pull/3917

**Comment by jucktnich** [comment]
I've seen this https://github.com/corona-warn-app/cwa-app-android/pull/3917 and I don't know if it's planned, but I think you should not only be able to get to this menu via the three dots menu, but also if you click on the event for which you want to warn.

**Comment by Ein-Tim** [comment]
@jucktnich 

If I understand the description of https://github.com/corona-warn-app/cwa-app-android/pull/3917 correct, it's indeed planned that you can only access the screen via the three point menu, see the "How to test" section in the description of the PR.

> How to test:
> 1. Home Screen -> "Planning an event?" card
> 2. **Three point menu** -> "In Vertretung warnen"
> 3. ✨ Tadaaa ✨

**Comment by jucktnich** [comment]
@Ein-Tim the integration of this could be planned for a different PR

**Comment by Ein-Tim** [comment]
@jucktnich Do you think your proposal was implemented with CWA version 2.9? Do you miss anything?

**Comment by jucktnich** [comment]
Closing this as implemented.

**Comment by jucktnich** [comment]
Thanks to all of the developers, you did and do a great job. It's just a pleasure to work with you guys.

**Comment by dsarkar** [comment]
Dear @jucktnich and dear community, Thanks for contributing in this project. I will forward your message! Thanks again, best wishes, DS

---
Corona-Warn-App Open Source Team
