### ISSUE TITLE
Allow backup of contact-journal & event-registration store

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#500]
## Feature description

The contact-journal store, as well as the event-registration store should be included in backups.

## Problem and motivation
An iOS update just ripped all my data of my iPhone, luckily I was able to restore nearly everything. In fact, I was able to restore everything but CWA data. That RPIs aren't included in a backup is one thing, that's tracked in #8, but I wonder why the contact-journal & the event-registration store aren't included in the backup. 
This would really be helpful and also very useful!

---

## Related issues

- #8 
- #324
- https://github.com/corona-warn-app/cwa-documentation/issues/504

----
Internal Tracking-ID: [EXPOSUREAPP-7217](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7217)

**Comment by Ein-Tim** [comment]
Just checked, this is already implemented under iOS. The behavior on Android seems to be completely different (no backups are allowed at all). 

Please feel free to move to the Android repo.

**Comment by Ein-Tim** [comment]
Update: I was forced to change to another phone and this time I lost my check-ins and contact journal entries, so not really sure what really the intended behavior under iOS is.

**Comment by gh47110815** [comment]
Same here. New iPhone - Restored using OOTB (out of the box) functionality from apple. Most Apps have restored my personal data - CWA: Everything is lost. So I have to wait 14 Days until full functionality is given again (regarding exposure checks). All Contact and Place History is lost - This is very, very disappointing!!! And I do not see any data security issues if these data would have been written to standard user space so that apple would be able to restore it. I would give this functionality a high priority if I could . even if it may be get necessary not so often.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
