### ISSUE TITLE
Add PCR test recommendation after red warning notification

### ISSUE THREAD

**Issue by di-sc** [corona-warn-app/cwa-wishlist#536]
## Current Implementation
Recommended actions for a user who got a red warning notification by the CWA is to _reduce contacts_ or if he/she has symptoms _contact the local health authority or a doctor_.

## Suggested Enhancement
Add a hint to the red warning notification to recommend a PCR test instead of a rapid antigen test, especially if the contact to the infected person was < 6 days.

### Explanation
A rapid antigen test is not as sensitive as a PCR test and cannot certainly detect an infection its early phase, when the person is infectious but does not have symptoms ([CoronaVirus Update - 84](https://www.ndr.de/nachrichten/info/84-Nicht-auf-Tests-und-Impfungen-verlassen,audio869676.html) (~min 48). But this is the phase where CWA should and is hopefully working, warning people in the early phase of an infection. This could be counterproductive that the people feel safe not having the virus, which might not be the case because of the wrong result of the rapid antigen test.
The CWA survey [WeHealth - Does it really work](https://www.youtube.com/watch?v=AE9ljDGNAus&t=3633s) seems to proof that. Most people decide to make a rapid antigen test and the rate of positive detected persons of rapid antigen tests are much lower than the rate of PCR tests.
![image](https://user-images.githubusercontent.com/54937900/120096146-16308d80-c12a-11eb-8f08-37763f6eee16.png)

## Expected Benefits
Increase rate of detected infected persons
Warn contacts early enough before they might infect others

----
Internal Tracking-ID: [EXPOSUREAPP-7980](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7980)

**Comment by ndegendogo** [comment]
Yes. Actually, the recommendation is to contact a doctor; and of course the doctor will know these limitations of RAT, and give the proper advice.
But: sometimes a doctor is not available fast (evening / weekend), and with the availability of rapid tests everywhere a user could decide  for the "do-it-yourself" solution and misinterprete / overinterprete a negative result.

**Comment by Ein-Tim** [comment]
There is a recommendation of CWA to get tested with a PCR test. 

If you've a high risk encounter you'll see this:

<img src="https://user-images.githubusercontent.com/67682506/120099569-729ca880-c13c-11eb-90e3-3e016411013f.png" width="300">

The FAQ entry linked is: 
https://www.coronawarn.app/en/faq/#red_card_how_to_test

This FAQ entry does not mention that you should take a PCR test, however https://www.coronawarn.app/de/faq/#rat_red_card_which_test does. 

Maybe we could combine these two FAQ entries in some way? 
That would be a start. I'll take care of that later on.

**Comment by Ein-Tim** [comment]
@di-sc Please see https://github.com/corona-warn-app/cwa-website/issues/1318.

**Comment by di-sc** [comment]
@Ein-Tim 
Thank you for creating the task, that's a good start.
Additionally I suggest also thinking about a hint for PCT test in the last sentence e.g.:

_Falls Sie sich testen lassen, **bevorzugt per PCR Test**, finden Sie weitere Informationen in der [FAQ zum Testablauf](https://www.coronawarn.app/en/faq/#red_card_how_to_test)._ 

The people who decide to make a RAT might not read the FAQ. Making a RAT is the easiest and cheapest way and if negative someone might think no further actions are necessary.

**Comment by Ein-Tim** [comment]
@di-sc 

I agree with you that we should add this information inside of the app itself, however this will take some time since the text probably has to be signed off by the RKI.

I'll wait for some feedback in https://github.com/corona-warn-app/cwa-website/issues/1318 and then go ahead and create a PR there, to get this information in the FAQ entry.

**Comment by MikeMcC399** [comment]
@di-sc 
The FAQ https://www.coronawarn.app/en/faq/#red_card_how_to_test has been updated to recommend a PCR test after receiving a red warning. See PR https://github.com/corona-warn-app/cwa-website/pull/1604 for details. @Ein-Tim has therefore also closed the issue https://github.com/corona-warn-app/cwa-website/issues/1318.

The screenshots from the app on https://www.coronawarn.app/en/screenshots/ are incomplete in the section "Risk Cards" because they don't scroll down, so I don't exactly how the full recommendation after a red warning reads, so I cannot explicitly verify it for the current version.

However, according to the screenshot from @Ein-Tim in https://github.com/corona-warn-app/cwa-wishlist/issues/536#issuecomment-850971844 above

<img alt="" width="300" src="https://user-images.githubusercontent.com/67682506/120099569-729ca880-c13c-11eb-90e3-3e016411013f.png">

he writes 
> The FAQ entry linked is:
> https://www.coronawarn.app/en/faq/#red_card_how_to_test

and now this entry contains the recommendation to take a PCR test.

It seems that this wishlist item is therefore effectively fulfilled, even though the PCR test recommendation is not embedded directly in the app, the link to the FAQ in the app provides the recommendation.

**Comment by MikeMcC399** [comment]
I worked out how to run a screenshot capture using `TracingDetailsFragmentTest.kt` in Android Studio with CWA Android 2.6.1 and the red card display for "Increased Risk" does include the link to the FAQ.

![TracingDetailsFragment_tracing_increased](https://user-images.githubusercontent.com/66998419/129450459-ba643fe0-64c0-4d29-8f6f-676d3d34f083.png)

**Comment by di-sc** [comment]
> It seems that this wishlist item is therefore effectively fulfilled, even though the PCR test recommendation is not embedded directly in the app, the link to the FAQ in the app provides the recommendation.

It is not completly what I expected but seems to be the maximum feasible.

@MikeMcC399 @Ein-Tim 
Thanks a lot for your work for the CoronaWarnApp.
You are doing a great and important job!
