### ISSUE TITLE
Scan screen of owh device to import test results

### ISSUE THREAD

**Issue by mfmburg** [corona-warn-app/cwa-wishlist#541]

**Comment by Ein-Tim** [comment]
Hey @mfmburg 

Thank you for contributing here!

I assume you meant to write "Scan screen of own device to import test results". So, you want to have the possibility to "upload" the QR-Code from your phone's screen into the app. 
If this is what you meant, this is tracked in #389. 

If you think your issue is a duplicate of #389, please monitor #389 and close this issue.
If I misunderstood you please elaborate a bit more on your proposal.

Thank you and stay safe!

**Comment by mfmburg** [comment]
Hi Tim,
You are right - this addresses the same issue. But somehow I was not patient enough during search / used the wrong key words... 
Thanks and take care
Martin
