### ISSUE TITLE
Ready CWA for immune escape variants

### ISSUE THREAD

**Issue by pkreissel** [corona-warn-app/cwa-wishlist#544]
## Feature description
Tests should be able to include VOC Status of the probe. If an immune escape variant is suspected, CWA should be more sensitive and also disregard vaccination status. 
Also People should be reminded to keep the app installed for the fall even if they have been vaccinated. 

## Problem and motivation
Great Britain's dominant variant is already lowering vaccine protection against infection.
More new variants might be able to infect even vaccinated people (with lower probability). They should keep the app installed and get tested if in contact with an infected person. 
This could help reduce the risk of more variants forming and reduce hospital burden in the fall among unvaccinated.

**Comment by MikeMcC399** [comment]
Related also to discussion in https://github.com/corona-warn-app/cwa-wishlist/issues/328.

**Comment by Ein-Tim** [comment]
@pkreissel 

FYI: If you register your vaccination certificate in the app (possible starting with the next version), this will **not** influence the risk calculation or how others will be warned if you test positive and decide to warn others via the Corona-Warn-App. 

But what's a valid point is that CWA should "know" (e.g. the lab has to transfer this too CWA) which variant of the virus you have and then adjust the risk scoring accordingly, so that others get warned e.g. after a shorter contact time if you have the British variant.

**Comment by heinezen** [comment]
FYI our stance from https://github.com/corona-warn-app/cwa-wishlist/issues/328 on new Corona variants is still the same:

> The RKI and the development team are closely monitoring the situation concerning the newer virus mutations. As said in the FAQ entry linked by @Ein-Tim , the risk calculation will be updated and adjusted as soon as new information is available. We will publish new information on this in the FAQ or here on Github when it becomes available.


----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
There is a new blog post on this subject. See https://www.coronawarn.app/en/blog/2021-07-08-cwa-virus-variants/.

**Comment by heinezen** [comment]
We will use https://github.com/corona-warn-app/cwa-wishlist/issues/328 for all official communication about mutations and variants from now on. I'll close here. Please move the discussion to the other thread.

----
Corona-Warn-App Open Source Team
