### ISSUE TITLE
List country restrictions/allowances when travelling using the digital vaccination certificate

### ISSUE THREAD

**Issue by treysis** [corona-warn-app/cwa-wishlist#557]
I read over at https://github.com/corona-warn-app/cwa-documentation/issues/634 that it will be possible in the future to check for the validity of the digital vaccination certificate in various countries. E.g. how long the last vaccination must have been in the past, or how long it will be accepted/valid after the last vaccination.

It would be great if that was available also as a list for better overview, not having to query every single country for an extended trip. E.g. show a list with all countries, next column with current status or from what date travel will be allowed/denied.

----
Internal Tracking-ID: [EXPOSUREAPP-8105](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8105)

**Comment by Ein-Tim** [comment]
@treysis Are you referring to https://github.com/corona-warn-app/cwa-documentation/issues/634?

#634 is not a valid link in this repository.

**Comment by thomasaugsten** [comment]
You will find this list on https://reopen.europa.eu/de

**Comment by MikeMcC399** [comment]
https://reopen.europa.eu/de offers apps to answer this request, although the app itself does not take into account the user's EU Digital COVID Certificate status:

- https://play.google.com/store/apps/details?id=eu.europa.publications.reopeneu
- https://apps.apple.com/us/app/re-open-eu/id1531322447

Thanks to @thomasaugsten for the link!

**Comment by MikeMcC399** [comment]
@treysis 
re: your comment in https://github.com/corona-warn-app/cwa-documentation/issues/634#issuecomment-864152765
> Yeah, it would be great to have this as a table, not having to query every country manually and do manual calculation.

I tried out the website https://reopen.europa.eu/de and the Android app and there is a lot of information presented. It probably wouldn't work well to just have a table because you would then end up scrolling a lot. Some countries like Spain also have different rules for different regions in the country.

**Comment by heinezen** [comment]
Hey @treysis 

Thank you for the request. This also goes into a similar direction as https://github.com/corona-warn-app/cwa-wishlist/issues/151 I guess. We have notified the dev team and they will think about the proposal.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Could you check if the implementation in version 2.6 fits what you proposed @treysis?

**Comment by Ein-Tim** [comment]
@treysis Did you have time to check whether CWA version 2.6 fulfills your proposal?

**Comment by Ein-Tim** [comment]
@dsarkar I suggest to close this issue.

**Comment by MikeMcC399** [comment]
Slightly off-topic, since this repository does not cover the CovPass App, but I want to mention that this functionality is also now available in CovPass App. See https://digitaler-impfnachweis-app.de/en/faq:

**Is my certificate valid for travel to an EU country?**

If you are planning to travel to an EU country, you can check whether your Digital COVID Certificates are valid in the CovPass-App in advance without obligation. ...

**Comment by Ein-Tim** [comment]
Could you please close this issue @dsarkar?

**Comment by Ein-Tim** [comment]
Can we please finally close this issue? It was implemented in version 2.6, we're at version 2.14 now. It makes no sense to leave solved/implemented issues open for longer than absolutely necessary.

**Comment by dsarkar** [comment]
@treysis Thanks for contributing here, best wishes, DS
@Ein-Tim Thanks for the reminder!

---
Corona-Warn-App Open Source Team
