### ISSUE TITLE
Publish exact date and time when an update was published in the Google Play Store

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-wishlist#585]
## Current Implementation

Only the date of a release is published.

## Suggested Enhancement

See title.

## Expected Benefits

Give the users the chance to estimate the date and time when the staged rollout of a new version will be finished.

**Comment by Jo-Achim** [comment]
I don't know if that is possible. In the past it was said that new releases (from Google) are deliberately distributed with time delays in order to prevent possible errors in the releases from affecting all users at the same time!? Or to incorporate 'necessary corrections'.

No matter how, but then calculations would hardly be possible.

**Comment by DerVogel2020** [comment]
The time when the release button (or whatever it is in Google Play) is pressed should be known to at least one person. So the exact time can be published.

**Comment by Jo-Achim** [comment]
Ah, I misunderstood that. Based on an action by a user (e.g. 'release button'), Google should show him when the staged rollout of a new version will be completed!?
Still: I'm not sure.

**Comment by heinezen** [comment]
@DerVogel2020 

The rollout is usually started at the same time as the release blogpost is published (e.g. 10:00, 12 July for [CWA 2.5](https://www.coronawarn.app/de/blog/2021-07-12-cwa-version-2-5/)).

I'm not sure if specifying the exact time helps because the time users get the update can also depend on other factors

* The time that the Play Store/App Store fetches for updates, which is determined by things we cannot influence (battery charge, last update, user settings, ...)
* If a rollout is stopped (which has happened in the past) and we push a fix, the rollout is restarted. That also means that an additional 48h are necessary to complete the rollout

Generally, on day 3 after the rolout has started, everyoe should have gotten the update. 

----
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
@heinezen Ok, accepted.

But then the hint "Hier steht Nutzer*innen die neue Version der Corona-Warn-App über die nächsten 48 Stunden zur Verfügung." should be changed.
