### ISSUE TITLE
Allow registration of BärCODE (BaerCode) Test and Vaccination Certificate QR-Codes

### ISSUE THREAD

**Issue by your-highness** [corona-warn-app/cwa-wishlist#604]
## Feature description
In May 2021 Berlin Institute of Health (BIH) and Berlin Senate started an open protocol for certificate verification - called "BärCODE" (BaerCODE) (see https://www.heise.de/news/Der-BaerCODE-Digitale-Signatur-als-Corona-Test-oder-Impfnachweis-6050483.html?seite=2 )

An Client-side app is not needed: The BaerCODE certificate PDF can be saved digitally or printed to be shown for verification via the free https://scan.baercode.de/ website. 

Many institutions (test centers, Charité vaccination office) automatically issue BaerCode certificates (see https://www.baercode.de/teststellen-und-labore & https://www.baercode.de/teilnehmende-einrichtungen ). 

A prototype has successfully been used in a concert of Berlin philharmony orchestra 

## Problem and motivation
**Usage of BaerCODE is free and should be encouraged:** 
>  ![grafik](https://user-images.githubusercontent.com/1949888/127128420-e03b8e66-3690-4c13-a24e-fcd95bb0532f.png)
>    https://www.baercode.de/faq

It would be very helpful to allow for registration of BaerCODE QR codes in CWA. Currently the following error is displayed indicating BaerCODE is not yet a valid code:
> ![grafik](https://user-images.githubusercontent.com/1949888/127127921-0ae7f0c4-b2aa-4920-81a5-f6680cb46db0.png)

## Is this something you're interested in working on
No

**Comment by jucktnich** [comment]
Is the BärCODE better in some way, or should Berlin just change to the EU Certificates?

**Comment by your-highness** [comment]
I don't know in which way it should be "better". It's used extensively and it would be advised to incorporate it in CWA.

**Comment by jucktnich** [comment]
Yeah, but if it's not better, I guess they'll change step by step to the European system, so if this would be integrated, no ones using it.

**Comment by your-highness** [comment]
Let devs decide. Surely Bärcode devs can help with development.

**Comment by MikeMcC399** [comment]
@your-highness 
The error code you see `HC_PREFIX_INVALID` is explained in https://www.coronawarn.app/en/faq/#hc_prefix_invalid where it says:

"Under the tab 'Certificates' the app can only scan 'EU Digital COVID Certificates'."

If you scan an EU Digital COVID Certificate with a regular QR scanner you will see a long code which starts with `HC1:`

If you try to scan any QR code which does not start with `HC1:`, using the Corona-Warn-App certificate scanner, then the app will give the `HC_PREFIX_INVALID` error code.

The supported certificates are explained under https://www.coronawarn.app/en/faq/#eu_dcc_which which also links to the [EU Digital COVID Certificate](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en) information.

The BärCODE initiative is surely an interesting implementation, however since the EU countries (and 6 other non-EU European countries) have agreed on a common standard which went live on July 1, 2021, I'm not sure that there is room for alternative concepts and implementations within the framework of the Corona-Warn-App, the CovPass App and the CovPassCheck App.

It would be good to hear from the initiators of BärCODE how they view the EU Digital COVID Certificate implementation.

**Comment by thomasaugsten** [comment]
There are no plans to add non EU vaccination certificates into the apps.

**Comment by heinezen** [comment]
Hello @your-highness ,

Your proposal is interesting, but we currently don't see the advantage of BärCode over the EU certificates. The EU certificates provide the same functionality, are standardized across Europe and are also issued for free. The situation was different in May, but EU certificates seem to be the better option right now. Could you maybe provide more reasons what advantages BärCode would have over EU certificates?

Additionally, I don't think that BärCode infrastructure is actively developed anymore. The last news from their website are from a month ago (https://www.baercode.de/aktuelles/philharmonie-konzert-in-der-waldbuehne-mit-bih-baercode) and so is the activity in their development repository (https://gitlab.com/ponci-berlin).

----
Corona-Warn-App Open Source Team

**Comment by your-highness** [comment]
Hello @heinezen and  @MikeMcC399 

You are probably right that the Baercode got pretty much deprecated after digital EU vaccination certificates got finally sorted out (July 1st 2021). 

The only advantage would be that test centers in Berlin still issue the Baercode for test certificates. 

For vaccination certificates one could get a EU certificate in a pharmacy by showing the immunization passport.

Thanks everyone for diving into this topic. For me the issue is closed.

**Comment by aki-ks** [comment]
BärCodes are still actively used by many Test-Centers.

My Test-Center in Stuttgart (https://dein.coronatest.de/) that offers PCR-Tests does for instance only issue BärCodes.

Even after consulting their support, they told me that they are **not** able to issue Digital EU Covid-Certificates, only Bärcodes.

**Comment by thomasaugsten** [comment]
The guidelines from the KBV are clear in this topic
https://www.kbv.de/html/1150_53277.php#:~:text=08.07.2021%20%2D%20B%C3%BCrgertests%20werden%20ab,Coronavirus%2DTestverordnung%20des%20Bundesgesundheitsministeriums%20vor.
