### ISSUE TITLE
"merge" people together in case of typos in the certificates and show more info in the certificates tab

### ISSUE THREAD

**Issue by msschuh** [corona-warn-app/cwa-wishlist#607]
I'm sorry that this does not quite match the Feature description / Problem and motivation scheme, but in this specific case it feels better to reverse it.  (To me it feels more like a fix to an existing feature)
## Problem and motivation

I have experienced the following problem with the certificates:
Since I have a middle name and some testing-stations do not fill in my middle name in the certificate, I have now two "different" people on the certificates tab. However, both of them are me. This way, I once showed the wrong certificate (a test that was already too old) for verification because on the "certificates" tab you do not even see that date of the test, type of certificate, ... - it is just a "blind" selection.

## Feature description
I would like to see two small changes:
1) I would just like to be able to tell the app that several "different" people are in fact one and be able to group the certificates together.
The reason for this is that typos can happen when someone inputs a name or the date of birth into a form. Especially if you did not book an appointment for a test and the test-station just copys the data from the passport.

One could even do some internal verification: If two people have the same date of birth, the chance are not too bad they are the same. Or if they have exactly the same name but the date of birth differs, there might be a typo in here.
I'm not asking to be able to correct these data later, just to be able to group the accoriding certificates together.

The thing is: Even it is not your certificate, you were able to get the QR-Code for this certificate already if you could load it in the app.

2) A small adjustment on the "certificate-tab": Not only should the certificate say "Digitales Covid-Zertifikat der EU" and the name, but also should specify some data of the currently used certificate (Date + Type).
## Is this something you're interested in working on

Sorry, but no.

**Comment by heinezen** [comment]
Hello @msschuh 

> I would just like to be able to tell the app that several "different" people are in fact one and be able to group the certificates together.
The reason for this is that typos can happen when someone inputs a name or the date of birth into a form. Especially if you did not book an appointment for a test and the test-station just copys the data from the passport.

This is not possible because the certificates are only valid in combination with your ID card/passport. Therefore, If there is a typo in the certificate, the certificate will be invalid as it does not match the data on the ID card/passport. The only way to solve this would be to re-issue the certificate with the correct name or date.

>  A small adjustment on the "certificate-tab": Not only should the certificate say "Digitales Covid-Zertifikat der EU" and the name, but also should specify some data of the currently used certificate (Date + Type).

This is already implemented. When you tap on a certificate, the certificate type and the date of issue should be displayed below the certificate.

I hope this addresses your requests. I will close this issue since your 1. feature request is not possible and your 2. request is already implemented.

----
Corona-Warn-App Open Source Team
