### ISSUE TITLE
Compatibility with Immuni or other similar apps

### ISSUE THREAD

**Issue by ValeVolc** [corona-warn-app/cwa-wishlist#62]
Hi!

I checked for an answer, but couldn't find one, so I hope I'm not redundant. 
I would like to understand if Immuni and Corona-Warn communicate with each other since (to my shallow knowledge and understanding of the technology used) they seem to work in a pretty similar way. 
If they communicate, great!
If they don't, is it something that could be implemented? What is the purpose of having two (or more, I don't know about other countries) apps that work in the same way but cannot communicate with each other? Especially in a moment when borders are open and people are restarting to travel.
Privacy issues?

-------------
Internal Tracking ID: EXPOSUREAPP-2131

**Comment by daniel-seidl** [comment]
I would like to add to this that, even if it is not possible to make the Apps communicate with each other, it would be great if one could have more than one exposure tracking app active... I live near the swiss border and when I try to activate exposure tracking in the Swiss App it automaticalle disables tracking in this App and vice versa. Is this due to the API provided by Google / Apple?

**Comment by MichaelPFrey** [comment]
My understanding is that "in theory" making corona-warn-app, swisscovid and immuni compatible is as "simple" as exchanging the infected keys between the national servers.

Problematic is, that any app using googles and apples API can (and does) use different criteria. So in some corner cases, one app might classify a contact as borderline low risk (displayed as low risk), while an other app presented with the same keys classifies the contact as border line high risk (displayed as high risk).

An other problem (at least in my opinion) is that Swisscovid shows "day since potential exposure" ([see screenshoot](https://bag-coronavirus.ch/wp-content/uploads/2020/06/app-de-cut.jpg)) - that could become a problem as corona-warn-app users did not sign up for that. (Privacy Concern) Note that swisscovid is very intentionally trying to access information the API normally would not want to expose (see [API Usage](https://github.com/DP-3T/dp3t-sdk-android/blob/master/EXPOSURE_NOTIFICATION_API_USAGE.md#detecting-exposure)).

> ... when I try to activate exposure tracking in the Swiss App it automaticalle disables tracking in this App and vice versa. Is this due to the API provided by Google / Apple?

Yep, in practice only one app can access the API.
The API has a hard limit on how many request it is allowing per day. [Page 9, provideDiagnosisKeys()](https://static.googleusercontent.com/media/www.google.com/de//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf?page=9)
Any app will try to use the available API calls.

Corona Warn App is close to exhausting the apple limit of 20 API calls per day by providing the infected key files of the past 14 days, resulting in 14 API calls.

Swisscovid  provides the infected key files for 10 days - allowing swisscovid to check twice a day. [DP-3T API Usage](https://github.com/DP-3T/dp3t-sdk-android/blob/master/EXPOSURE_NOTIFICATION_API_USAGE.md#rate-limit)

There are some discussion for corona-warn-app to use the API calls more efficiently - but that is discussion and would likely be used to update the status more frequently (not to spare API calls for foreign apps).

Swisscovid intentionally calls the API inefficiently (passing each days infected key file separately) so that the App can display "day(s) since potential exposure". [DP-3T API Usage](https://github.com/DP-3T/dp3t-sdk-android/blob/master/EXPOSURE_NOTIFICATION_API_USAGE.md#detecting-exposure)

**Comment by MikeMcC399** [comment]
The EU Interoperability Gateway has gone live. See https://www.coronawarn.app/en/blog/2020-10-19-version-1-5/.

[Immuni from Italy](https://www.immuni.italia.it/) is one of the first countries to join the EU Interoperability Gateway.

- [Full list of EU apps](https://ec.europa.eu/info/live-work-travel-eu/health/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_en)
- [List of countries currently connected with Germany to EU Interoperability Gateway](https://www.coronawarn.app/en/faq/#interoperability_countries)

https://github.com/corona-warn-app/cwa-wishlist/issues/79#issuecomment-713655496 is also related.

**Comment by heinezen** [comment]
Compatibility is being continually expanded since CWA version 1.5 by using the EU Interoperability Gateway. I think this feature request is solved then.

----
Corona-Warn-App Open Source Team
