### ISSUE TITLE
[Statistics cards] Start on a statistics card

### ISSUE THREAD

**Issue by jucktnich** [corona-warn-app/cwa-wishlist#625]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [?] Enhancement request is specific for iOS only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

If you start the app and scroll down to the statistics, you start on the edit/add new incidence screen.

## Suggested Enhancement

Start on a statistics card, probably the most right local or the nationwide card.
## Expected Benefits

Start where you most likely want to be.

**Comment by MikeMcC399** [comment]
I can't see this issue on Android, so perhaps it is an intermittent iOS bug?
I see this issue was first posted to iOS anyway.
If it comes back or persists on iOS then probably a bug report for iOS would be good.

Also check if it is still relevant for the current version, since the posting and comments concern the previous version.

**Comment by ndegendogo** [comment]
Yes. Seems fixed. Tested as follows:
- start cwa, main screen, scroll statistics to the far left (edit / new incidence)
- scroll up and down
- see animated auto-scroll to a true statistics card

cwa 2.7.2 / iOS 14.4.1

@jucktnich please confirm

**Comment by jucktnich** [comment]
Couldn't reproduce close as fixed/implemented
