### ISSUE TITLE
Twitter Suggestion: Implement more than just one PCR test error status ("Invalid Test") when a test could not be evaluated

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#631]
## Current Implementation
Currently, when a test could not be evaluated, for which reason whatsoever, the error message is very generic and only says "Invalid test. Your test cannot be evaluated."

Here's a screenshot:

<img src="https://user-images.githubusercontent.com/67682506/130694862-15a8277f-fa6e-42fd-8d00-e67378429d23.png" width="300">

## Suggested Enhancement
The error message should more precise about what exactly is the issue with the sample. 

## Expected Benefits
Sometimes a test is "inconclusive", that is not the same as "cannot be evaluated.". 
So, first benefit would be to avoid untrue statements and second would be better UX & help users with giving them a better explanation what happened.

## Additional information 
This is a report based on the feedback I received from a Twitter user: https://twitter.com/Simmerl19/status/1430219966507372545?s=20

---
Internal Tracking ID: [EXPOSUREAPP-13534](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13534)

**Comment by fynngodau** [comment]
I think you should add to the title that this only applies to PCR tests.

For rapid tests, invalid results usually only have one reason (besides that a sample was lost, which I'm sure staff at a testing station would not like to admit): that the test kit – more precisely, the cassette that you drip the probe on – was damaged, for instance, due to exposure to too high temperatures. Then, the liquid does not run through the window in the cassette correctly, but smears the red color across the indicator window.

A rapid test can furthermore not be evaluated as valid but inconclusive, because if the control line is visible, the slightest change in color in the test line is to be evaluated as positive – there's no room for "oh, let's try again and see what happens this time before we report it as positive".

**Comment by Ein-Tim** [comment]
This issue stayed unmirrored to JIRA for a prolonged period of time. Please mirror it to JIRA now.

**Comment by Ein-Tim** [comment]
Please mirror this issue to JIRA now @dsarkar / @larswmh.

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13534](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13534)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
