### ISSUE TITLE
Rapid Test Profile: Add extra field for gender

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#641]
## Feature description

Currently the Rapid Test Profile does not include a extra field where the user could enter their gender. An extra field should be added where the user can enter their gender.

## Problem and motivation
When a rapid test station uses the rapid test profile to register the user, the staff from the testing station has to manually add the gender. So the motivation is to make the process more easy for testing stations.

---
Internal Tracking ID: [EXPOSUREAPP-12174](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12174)

**Comment by fynngodau** [comment]
I think it should be done the other way round and the gender field should be removed from the server-side RAT application since:

* it is not relevant for billing
* it does not appear in the certificate
* it is not shown on the German identity card
* (I have not been to a site that uses the Corona-Warn RAT application, but I could imagine that) it is not transparent to the user whether the data is recorded correctly, and if it is recorded wrongly,
* it may discriminate against individuals whose appearance does not align to gender norms.

**Comment by thomasaugsten** [comment]
Unfortunately the medical gender is relevant in case of a positive test which needs to be reported to the health authority

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Will the gender field be added soon? 

A user on Twitter again pointed out that the field is needed and it would be very helpful for all testing sites if they wouldn't have to add this field manually.

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12174](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12174)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
