### ISSUE TITLE
Make CWA interoperable to itself

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-wishlist#68]
## Current Implementation

CWA becomes interoperable to similiar implementations by interface discussions.

## Suggested Enhancement

CWA is open source. If a country derives its own implementation, it should be interoperable to all instances of CWA automatically.

## Expected Benefits

No more interface discussions necessary.

--------
Internal Tracking Id: EXPOSUREAPP-2129

**Comment by Ein-Tim** [comment]
Has this been fixed with the implementation of the Transnational Exposure Logging in version 1.5? Or what exactly is meant with "interoperable to itself"?

Thanks to the usage of the Exposure Notification Framework/System from Apple/Google your phone already exchanges Bluetooth Beacons with all other phones that have the ENF/ENS active, regardless which contact tracing app is active on their phone. 
However, for warnings to work, the countries have to be connected to the EFGS (European Federation Gateway Service). More infos can be found in https://www.coronawarn.app/en/faq/#interoperability_countries

**Comment by gitbrueck** [comment]
A clone of CWA would be interoperable as well, yes. The implementation is successful.
