### ISSUE TITLE
Add support for Huawei COVID API in HMS 5.0

### ISSUE THREAD

**Issue by coder66** [corona-warn-app/cwa-wishlist#71]
HMS 5.0 has an API for COVID tracking, like Google and Apple.

Task: add support so that users on Huawei devices without Google Services can also use the app. 

---------
Internal tracking Id: EXPOSUREAPP-2123

**Comment by SonaliDK** [comment]
Hi @coder66,

Thank you for your proposal. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

SD

Corona-Warn-App Open Source Team

**Comment by Huatik** [comment]
Hi @coder66,

are there any news? I called today ur technical service team and ask them for this app. 
Because I'm not able to use it. Also as download from the official website. I need GSF which I'm not having. I had only HMS Core 5.0, so at least AppGallery access.

What I can't believe and hope this comes from an misunderstanding, ur technical service team said to me, ur waiting for an reply from the US if u could support Huawei or not. I can't believe that. This would tell me, ur not free to develop and the USA can say what u could do or not. If this is true, than... sorry for germany

**Comment by thomasaugsten** [comment]
Hi

we are not waiting for a reply. Huawei is planning to integrating the ENF in HMS when this is done the CWA can access the ENF in the same way like GMS.

**Comment by larswmh** [comment]
Closing this issue as its related internal ticket was set to obsolete.
