### ISSUE TITLE
Prepare for EU change reg. period of validity of vaccination DCCs which will come into effect on 01.02.2022

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#726]
### This is an informational issue.

---

## Current Implementation
Vaccination certificates have a technical validity of one year since the issuing, after 6 months, the user is seeing a hint that they are eligible for a booster shot.    

However, the certificate is still valid. 

## EU change which comes into effect on 01.02.2022

See this press statement from the European Commission: https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837

It says:

"Today, the Commission adopted rules relating to the EU Digital COVID Certificate, establishing a binding acceptance period of 9 months (precisely 270 days) of vaccination certificates for the purposes of intra-EU travel."

So this means, after 9 moths, one which does not have a booster shot, can't use the vaccination DCC to travel intra-EU anymore.

## Prepare for this change

Make CWA ready to display this information as soon as possible to prepare the user for this change so that the user has time to prepare and make an appointment for a booster shot. Make it clear that this change does not affect the vaccination status in Germany & the certificate will still be accepted for entry to e.g. restaurants.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Do you know what the current rule definition is for informing users about getting a CWA booster and if the rules are available and viewable online?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I suggest you take a look at #684, especially https://github.com/corona-warn-app/cwa-wishlist/issues/684#issuecomment-990761609.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thanks for the links to decode the booster rules!

Looking at

`{"identifier":"BNR-DE-0300","version":"1.0.0","hash":"cd7defef43c2c0edb115090e669c2bb9028608e247c71b3d0f44728a3df4126f"}`
https://distribution.dcc-rules.de/bnrules/cd7defef43c2c0edb115090e669c2bb9028608e247c71b3d0f44728a3df4126f

BNR-DE-0300

"The Federal Ministry of Health recommends that all persons who have not had a proven case of the coronavirus (SARS-CoV-2) and who obtained their base vaccination more than six months ago arrange a vaccination appointment or discuss the benefits of getting a booster shot with their doctor. Scientific studies confirm that booster shots provide a higher level of protection against becoming infected with COVID-19.\n\nAs your saved certificates indicate that you belong to this group of persons and have not yet received a booster shot, we would like to inform you of this recommendation. (Rule BNR-DE-0300)\n\nThis notification is exclusively based on the certificates stored on your smartphone. The data was processed on your smartphone. No data was transferred to the RKI or third parties."

it seems from the text that your request is already answered, **however** ...

it appears at the moment that the rule is only applied for people older than 70 years of age, even though it doesn't say anything about that in the text (which it does for rules BNR-DE-0100 & BNR-DE-0110):

```
          {
            "plusTime": [
              {
                "var": "payload.dob"
              },
              70,
              "year"
            ]
          }
```

I don't know if that is intentional or not.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks for your investigation, but it seems you have misunderstood me. The European commission has today made public that EU vaccination certificates will loose their validity 9 months after the vaccination, if it's not a booster certificate. 
This change should IHMO be communicated clearly in the app & the best way doing this is changing the booster notification rules. 

Do you understand what I mean?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I thought the booster notification rule BNR-DE-0300 would cover your request if it is not made dependent on being for people older than 70 years of age. It would trigger after 6 months, but it sounds like you expect either different rule logic or a different text.

Perhaps you could elaborate what you think should trigger the rule and what the text of the rule should say?

I will follow the answer to your related question in https://github.com/corona-warn-app/cwa-documentation/issues/754#issuecomment-998952149.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Let me explain it from the very scratch:
Today, the European Commission decided that EU digital vaccination certificates will loose their validity 9 months after the basic immunization. 
See also https://www.tagesschau.de/ausland/europa/impfnachweise-eu-gueltigkeit-101.html, which says:

"EU-Impfzertifikate ohne Booster sind künftig spätestens neun Monate nach der Grundimmunisierung ungültig. Die Regelung tritt am 1. Februar in Kraft, teilte die EU-Kommission mit."

(Which auto-translates to:
"EU vaccination certificates without boosters will in future be invalid no later than nine months after basic immunization. The regulation comes into force on February 1, the EU Commission announced.")

So, with this change in mind, I'd expect that there is a new booster notification rule which informs the user that unless they get the booster shot, they will loose their vaccinated status 9 months after the basic immunization. 

The notification should be sent **to all** users, who received their basic immunization more than 6 months ago, regardless of age or which vaccine was used.

I hope it's clearer now! 🙂

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thank you for explaining your suggestion. I understand.

**Comment by Th-St** [comment]
If implementing please take into account that EU states 270 days and not 9 months:
"Today, the Commission adopted rules relating to the EU Digital COVID Certificate, establishing a binding acceptance period of 9 months (precisely 270 days) of vaccination certificates for the purposes of intra-EU travel."
Source: [https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837](https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837
)

**Comment by Ein-Tim** [comment]
https://github.com/corona-warn-app/cwa-documentation/issues/784 opened regarding another change which will come into effect on 01.02.2022.

**Comment by Ein-Tim** [comment]
There are no hints in the app as of version 2.17.1. Traveling rules for Germany also haven't been updated, if I'm not mistaken (cc @vaubaehn, @mlenkeit). Other member states probably have to update their rules themselves.

**Comment by Ein-Tim** [comment]
This issue remains open as long as the travel rules have not been updated.

**Comment by Ein-Tim** [comment]
The travel rules have been updated and this issue can be closed now. https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=DE&rule=VR-DE-0004
