### ISSUE TITLE
Contact diary: add option to delete people and location to clean up diary

### ISSUE THREAD

**Issue by libuda** [corona-warn-app/cwa-wishlist#753]
## Feature description
Add an option to delete existing locations and contact people from the diary to clean up messy diary.

## Problem and motivation
After almost two years my diary got quite messy with locations and people I met. Quite a lot of them were only one time appointments eg. during vacation.

## Is this something you're interested in working on
No, I dont have to the skills to support... sorry.

**Comment by MikeMcC399** [comment]
@libuda 

- There is already an option to Edit People and Edit Places which allows individual deletion or deletion of all entries in either list. See also https://github.com/corona-warn-app/cwa-wishlist/issues/334.
- Also there is a request https://github.com/corona-warn-app/cwa-wishlist/issues/405 to make it easier to delete unused contact journal entries.

**Comment by Ein-Tim** [comment]
[Corona-Warn-App version 1.10 with contact journal is available](https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/) explains how to delete contact journal entries.

**Comment by libuda** [comment]
Thx for the feedback. Finally I found the option to delete locations and people... I will close the issue

**Comment by MikeMcC399** [comment]
- There is an FAQ entry [Contact Journal](https://www.coronawarn.app/en/faq/#contact_diary) which has a pointer to the blog post [Corona-Warn-App version 1.10 with contact journal is available](https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/) which includes a section "Deleting and editing data".

- Since this is not so easy to find, I requested a separate FAQ article to cover editing and deleting items in the contact journal. See https://github.com/corona-warn-app/cwa-website/issues/2314.

**Comment by MikeMcC399** [comment]
@libuda 

Thank you for letting us know that you succeeding in finding the right place in the app!

**Comment by MikeMcC399** [comment]
An FAQ article has now been published to help other users:

- [How can I edit or delete entries from the Contact Journal?](https://www.coronawarn.app/en/faq/#contact_diary_edit)
- [Wie kann ich Einträge im Kontakt-Tagebuch bearbeiten oder löschen?](https://www.coronawarn.app/de/faq/#contact_diary_edit)
