### ISSUE TITLE
Please only implement the reissue feature after the BfDI finished their audit on the feature (if there will be an audit)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#796]
## Current Implementation
From what I can tell from PRs it seems like the team is planning to release the reissue feature in version 2.19.

## Suggested Enhancement
Only release this feature **after** an audit was performed by the BfDI. If you don't know whether there will be an audit, I suggest to get in touch with the BfDI before releasing the feature.

## Expected Benefits
Avoid the situation as we have it now with the DCC ticketing feature.

**Comment by GisoSchroederSAP** [comment]
@All, we are working on a statement about the approach to planning and implementing features in the app. Please keep in mind that our objective is to stay as up-to-date as possible with the app. However, development (including testing) will always lag behind the current decision-making process.
So, yes, we are aware that the released version may not always reflect national and/or regional rulings or dynamically changing decisions and recommendations of the authorities. Obviously, we will not and cannot implement and publish anything that has not been approved by the stakeholders and the necessary legislative authorities (including BfDI).However, in the interest of time, we try to parallelize some activities within the SCRUM approach. In rare cases, this may also lead to redundant coding, but in terms of risk assessment, we accept this risk to be able to ensure timely delivery.

Be assured, we will use the momentum and we are on track to cover the ongoing legislative amendments with the next versions of the app.

Please remain patient.

**Comment by Ein-Tim** [comment]
The feature is included in version 2.19.0, however, it has been deactivated server-side:  https://github.com/corona-warn-app/cwa-app-ccl/pull/47

I'm closing this issue now, which does not mean I'm not interested in the statement @GisoSchroederSAP announced.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Is there actually an update available on the report you were planning to make 7 months ago?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> The feature is included in version 2.19.0, however, it has been deactivated server-side: https://github.com/corona-warn-app/cwa-app-ccl/pull/47

Your previous statement is out of date since the reissue functionality became available with CWA 2.20 (see https://www.coronawarn.app/en/blog/2022-03-30-cwa-2-20/).

The current privacy document https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf covers this. See page 19 "o. Update feature for COVID certificates".

The published [DSFA](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) has not been updated since CWA 2.15 and still carries the document version number 1.20 from December 2021. I would expect a detailed description of the update feature to be part of this document. See issue https://github.com/corona-warn-app/cwa-website/issues/2821 and Internal Tracking ID: [EXPOSUREAPP-12963](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12963).

Since the reissue function is covered in the privacy document (Update feature for COVID certificates) I assume that all necessary approvals were done. The fact that the [Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland, Öffentliche Version, Version 1.20, 09.12.2021](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) is out of date however means that further details are not available to the community.

Perhaps an updated version of the DSFA document could be published?
