### ISSUE TITLE
Archive warning feature

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#806]
## Feature description

The app should be extended with a feature which allows the user to archive increased & low risk warnings.

## Problem and motivation
Many users are complaining that the warning stays until 14 days since the encounter have passed and there is no option to influence this, not even with a negative test.

Implementing an "Archive" feature for warnings, would be a benefit for these users, who don't want to see the warning for the next days or/and want to be notified again if there is another increased risk exposure.

---
Internal Tracking ID: [EXPOSUREAPP-12128](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12128)

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12128](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12128)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
There are more and more users reporting on Twitter that they get warned form their CWA because neighbors have been tested positive.
I'm one of the users affected & I have to admit that, after assessing my risk and knowing that I had no contact to the infected neighbors, I'm just ignoring the warning.

Archiving it would be quite nice, as I would then receive a push notification if there is another exposure. Also, I would instantly see in the app, if there is a new encounter, as at the moment, my risk card is red anyways.

**Comment by MikeMcC399** [comment]
I support this wishlist item! I would like to be able to dismiss red warnings which are irrelevant.

The FAQ article [Why do I receive a risk warning for a date when I had no contacts / did not leave the house?](https://www.coronawarn.app/en/faq/#risk_encounter_doubted) explains how false positive exposure risk warnings can occur.

Especially for the situation where somebody knows they had no contacts on a certain date then the warning can be safely dismissed. Instead a red tile warning persists on the device for up to 14 days.

Yesterday for instance I had a warning on a device that never leaves my desk at home. I can guarantee that no other person, apart from myself, was physically near that device yesterday. I do not have an infectious status myself based on any tests, so this warning is definitely a false warning which can be ignored. Unfortunately the app gives me no way to mark the warning as false and to dismiss it.

Keeping the warning status clean, by purging implausible warnings, reduces the likelihood of the [wolf syndrome](https://en.wikipedia.org/wiki/The_Boy_Who_Cried_Wolf). If the app is continuously showing red, because of false positives, a user is less likely to pay attention to it if a true positive risk warning is shown.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
