### ISSUE TITLE
Reduce contact journal amount of days stored to 10

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#815]
## Current Implementation
I can see today + the last 15 days in the contact journal.

## Suggested Enhancement
Reduce the days stored to today + 10.

## Expected Benefits
Be consistent with the check-in & exposure logging feature.

Background: https://github.com/corona-warn-app/cwa-app-ios/pull/4324

Ping @thomasaugsten, is this planned?

---
Internal Tracking ID: [EXPOSUREAPP-12221](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12221)

**Comment by larswmh** [comment]
Thanks for your enhancement request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12221](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12221)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The [CWA 2.20 announcement](https://www.coronawarn.app/en/blog/2022-03-30-cwa-2-20/) says:

"**Display of increased risk shortened from 14 to 10 days**

Furthermore, as of version 2.20, the CWA only looks at the last 10 days for calculating the risk of infection and not the last 14 days as before. This is in line with current quarantine specifications. A red tile therefore automatically turns green again on the 11th day after the last risk encounter. As before, users cannot reset the red tile to green manually or by registering a negative test result, as they can still develop symptoms because of the risk encounter within these 10 days (more information [in this blog](https://www.coronawarn.app/en/blog/2021-12-15-cwa-red-tile-guidance/))."

so it certainly would make sense to shorten the number of days recorded in the Contact Journal correspondingly to 10 days. Also the number of days available to be exported to the health authority would be reduced to 10 days.

**Comment by Ein-Tim** [comment]
@thomasaugsten / @larswmh 

Could you please mirror this to JIRA / take note:

I wrote with a Twitter user, who was very confused that risk exposures disappeared from her contact journal. Turns out: The exposure was more than 10 days ago, thus it disappeared. 
The current implementation is very confusing to users and needs to be changed soon! 

Link to Twitter: https://twitter.com/der_nalin/status/1534998807393484802?s=21&t=SjuVCVy6zyCa6Tq03X5lpw

**Comment by larswmh** [comment]
@Ein-Tim thanks for forwarding this. I'll add this to the internal ticket

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this feature to be implemented. I'm therefore closing this issue.
