### ISSUE TITLE
Exportable PDF/certificate for positive test results

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#822]
## Feature description

Version 2.21 will offer the feature to request test results from other family members via the Corona-Warn-App. 

To avoid confusion, CWA will show the name of the person tested next to the test result.

If the test is positive, it should be possible to create an exportable PDF, which includes the following information:
- Date of test registered in the CWA
- Date of test result received in the CWA
- Name
- Date of birth

## Problem and motivation
Test centers who would like to use a CWA-only solution currently don't have the ability to send some sort of "positive test certificate" via the app. 

Also, users are frequently asking for such an feature: https://twitter.com/valentinthoss/status/1510280433543663631?s=21&t=OWEPt_YkhRqpo36MRDZUWw or in https://github.com/corona-warn-app/cwa-app-android/issues/4718.

---
Internal Tracking ID: [EXPOSUREAPP-12624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12624)

**Comment by larswmh** [comment]
Thanks for your feature request @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12624](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12624)

---
Corona-Warn-App Open Source Team

**Comment by robinduerhager** [comment]
As mentioned in #869 i want to extend this feature request with the ability to download any test result / labor report regardless of the tests status.

In addition to your mentioned points @Ein-Tim , i think information like `laborname`, `testID` and `additional general information` that gives the downloadable pdf some sort of validity is crucial for this to work and be accepted in the community. 

In the best case as a user i would be able to just download the original labor report because as a user i want to be able to download any personal testresult so i will be able to send it to authorities or print it at home.

**Comment by dsarkar** [comment]
@robinduerhager Thanks for further refining the suggestion, forwarded to internal ticket.

**Comment by Ein-Tim** [comment]
@dsarkar 

A wish from my side: Please make it clear that @robinduerhager's proposal is an extension for my feature request, and not the original proposal.
Don't get me wrong, I love the idea of @robinduerhager and that would be the optimal implementation. However, this would require major changes in the process of how test results and with what information test results are submitted to the CWA.

What I proposed would be a bit less information for the user, but would be achievable without major changes in the test result process, as it is a change the CWA team could implement without having to ask laboratories, etc. to send more information to the CWA backend.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect to see any bigger features implemented. I'm therefore closing this issue.
