### ISSUE TITLE
Do not show new features screen if there are no new features

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#842]
## Current Implementation

Currently it is implemented that the "New Features" splash screen after a minor app update is shown, although the release does not contain any new features but only bug fixes (see e.g. https://github.com/corona-warn-app/cwa-app-ios/pull/4707).

## Suggested Enhancement
Do not show the new features screen if there are no new features in an app release.

## Expected Benefits
From a users perspective, showing a screen which tells me that nothing has changed does not have any value. It is not a helpful information and I can't do anything with the information that bugs have been fixed.

**Comment by Ein-Tim** [comment]
@dsarkar / @larswmh 

As this item is relevant for version 2.26, please mirror it to JIRA soon.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- There is a merged Android PR https://github.com/corona-warn-app/cwa-app-android/pull/5353 related to this request.

**Comment by Ein-Tim** [comment]
@MikeMcC399 This PR is good, as it prevents the splash screen being shown if I update from 2.24.1 to 2.24.2. However, I was talking about the fact that I will see a splash screen when updating form version 2.25.0 to 2.26.0 with the information that nothing has changed. This does not make sense.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Sorry that I misunderstood your request. 

- You're referring to the (currently unmerged) iOS PR https://github.com/corona-warn-app/cwa-app-ios/pull/4707

![iOS New Features 2.26.x](https://user-images.githubusercontent.com/77438487/182595507-e4a158b7-3a84-43f8-813a-98c8e251bb48.png "New Features")

Is there an equivalent PR for Android? I could not find one.

**Comment by Ein-Tim** [comment]
> Is there an equivalent PR for Android? I could not find one.

I don't think so. At least it is not included in https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.26.0-rc.0.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I would be fine if Android implemented the same message as the pending iOS PR (https://github.com/corona-warn-app/cwa-app-ios/pull/4707) if there are no new features.

In the past, new releases have always had new features, so if there is a release with no new feature I think that the app should say so instead of staying silent.

I realise there are different views on this: Some people would like no information at all. You would like an information screen only if there are new features. I would like an information screen for every minor version release (not patch release) whether or not there are new features.

**Comment by Ein-Tim** [comment]
> In the past, new releases have always had new features, so if there is a release with no new feature I think that the app should say so instead of staying silent.

Interesting. Could you explain why you'd like this information? How do you benefit from the information that nothing has changed?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This is just my personal preference. It also corresponds to the Project Office decision, as you will know from https://github.com/corona-warn-app/cwa-app-ios/pull/4707#issuecomment-1203817217.

It will be interesting to hear if there are other opinions about this.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Okay, understood! :)

I will feel free and ping a few other community members to see what they think: @fynngodau, @ndegendogo, @vaubaehn what do you think?

**Comment by ndegendogo** [comment]
I am a software developer. I am aware that **every** new version can bring changes / improvements / bugfixes / or, if I am unlucky, it can even introduce new bugs 👹👹

So I don't mind seeing a splash screen for a new release, even when there are no new features.
Actually, I would remove the last sentence if the menu "New functions" is empty.

Especially when I am suffering from a bug and waiting for a fix that is promised for the next version, then this splash screen has definitively a value for me.

Note that a non-developer user might see this differently and might indeed be confused.

**Comment by Ein-Tim** [comment]
@ndegendogo 

Thanks for your input! 

@GisoSchroederSAP Who is responsible to mirror issues to JIRA in August? Will this be done by you or someone from SAP/TSI?

**Comment by Ein-Tim** [comment]
Ok, seems like this won't be considered. Closing

**Comment by GisoSchroederSAP** [comment]
Thanks for the discussion here, folks.
We also had an internal evaluation whether or not to show the screen. The simple explanation is: Whenever we bring a new release, that is for a reason - something changed: be it a new function or a bug fix, or just a change in text or UI. 
To stay with good old practice of documentation, we allow ouselves to document the background of every new release.

- Is it crucial for the users? Probably not. As we see in the discussion above, there are pro's and con's 
- Is it crucial for placing the CWA on the market? Probably not, if no new functions can be offered.
- Are there legal, compliance or political requirements forcing us to bring up this "new features" screen? Not of my knowledge, it is just a decision made by our team to stay transparent.

So, instead of going to implement a conditional screen, we just go forward with the screen either documenting new features, give a brief statement about bugfixes or changes.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Thank you for the clarification!

<details>
<summary>Joke here</summary>

> To stay with good old practice of documentation, we allow ouselves to document the background of every new release.

I guess that's also why the documentation repo is absolutely up to date, right? 
SCNR 😉

</details>
