### ISSUE TITLE
Add information to confirmed new infections statistics card on weekend numbers

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-wishlist#845]
## Current Implementation
CWA displays strictly the numbers it gets from the RKI, without any disclaimer, information, etc. that the numbers may be too low on the weekend. 

## Suggested Enhancement
Add a hint in the app similar to the one displayed on the [RKI COVID-19 Germany dashboard](https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4).
The hint there is:
"Da am Wochenende nur noch wenige Gesundheitsämter und Landesbehörden Daten an das RKI übermitteln, werden keine Daten am RKI eingelesen, sodass es bei den absoluten Fallzahlen keine Veränderung zum Vortag gibt. Die Änderung der 7-Tage-Inzidenz im Vergleich zum Vortag beruht lediglich auf einer Änderung des Bezugszeitraums (jeweils 7 Tage vor dem Tag der Berichterstattung)."

## Expected Benefits
It's clearer to the user that the data is not accurate.

---
Internal Tracking ID: EXPOSUREAPP-13884

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The first time I saw the very low numbers I was quite confused and I thought that something was broken. Thank you for posting the information text explaining that there is little or no data transmission at the weekends currently!

Since changing the app text (if it is even approved and done) would take many weeks before it could be released maybe it would be better to update the FAQs first?

That would be the old FAQ article` #further_details` below or a new article:

- https://www.coronawarn.app/en/faq/results/#further_details "In-App statistics starting with release 1.11"
- https://www.coronawarn.app/de/faq/results/#further_details "In-App Statistiken ab Release 1.11"

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Updating the FAQs seems like a good idea to me, as a first step! 

I'll open an issue in the website repo later today!

**Comment by Ein-Tim** [comment]
- Issue https://github.com/corona-warn-app/cwa-website/issues/3087 opened

**Comment by Ein-Tim** [comment]
- FYI PR https://github.com/corona-warn-app/cwa-app-ios/pull/4755 & https://github.com/corona-warn-app/cwa-app-android/pull/5521 add a hint reg. this

**Comment by Ein-Tim** [comment]
@mtwalli or @sapcoder123 would you like to apply the `Fix 2.27` label here?

**Comment by Ein-Tim** [comment]
- PR https://github.com/corona-warn-app/cwa-server/pull/1893 added this change on server side. It seems like the change was already deployed and the 1% threshold is already in use.

**Comment by Ein-Tim** [comment]
Implemented.
