### ISSUE TITLE
Active time is easy to fake

### ISSUE THREAD

**Issue by v1nc** [corona-warn-app/cwa-wishlist#88]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug
The "active status" time is easy to fake. 

## Expected behaviour

The "active status" should be calculated with the real time, not with device time.
It should not be able to change "active status" behaviour by changing device time.
## Steps to reproduce the issue

1. Remove the app if installed
2. Install it again
3. Change device date to 2 weeks in the past before opening the app
4. Open the app, activate Exposure Logging
5. An API Error is displayed, close the app
6. Change device date back to today
7. Open the app
8. Click on "Exposure Logging" details and close them 2-3 times until the errors are gone
9. App now displays "14 of 14 days active" and  behaves as usual

## Technical details

- Mobile device: Nexus 5
- Android version: 6.0.1

## Possible Fix
Only use time from NTP servers to calculate "active time"

-------------
Internal Tracking Id: EXPOSUREAPP-2107

**Comment by dsarkar** [comment]
Hi @v1nc,

Thanks for contributing here. The app now shows days installed instead of days active, therefore this issue is obsolete now. We suggest closing this issue. 

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@dsarkar 

It's still possible to just set the time to the future and the "days since installation" are wrong (e.g. faked).
But, if the device time is wrong, the app shows an error and if there wasn't a risk calculation in the last 4 hours (connected to Wifi) or in the last 24 (connected to cellular) the app shows "Risiko-Überprüfung fehlgeschlagen."

**Comment by dsarkar** [comment]
@Ein-Tim Thanks. So, if not only wrong time, but also wrong date was detected, faking would not be possible, agreed?

**Comment by Ein-Tim** [comment]
@dsarkar Yes, agreed. Tested under iOS 14.5.1 on an iPhone 6s.

**Comment by Ein-Tim** [comment]
> Initially it is possible to change date and it shows more days installed, but then I gives the error "Risiko-Überprüfung fehlgeschlagen"

Yes correct, this is also what I have been experiencing. 

> So, my understanding is that at least for iOS this becomes obsolete. What do you think?

Yes, I agree that this seems to be "fixed" under iOS because of the "wrong time/date" notification which leads to "Risiko-Überprüfung fehlgeschlagen".

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback

**Comment by MikeMcC399** [comment]
@dsarkar 
> Thanks for contributing here. The app now shows days installed instead of days active, therefore this issue is obsolete now. We suggest closing this issue.

I agree that the issue should be closed. The repro steps no longer produce the result they previously did because of functional changes in the app. The app could have been installed for more than 14 days (in which case it shows no date installed) and during this time exposure logging could have been deactivated all the time. In other words it could have installed all the time, but was dormant.

Also there would be no benefit to faking the number of days installed. The use of the app is voluntary and these days all benefits are dependent on negative test status, vaccination status or recovery status. Nobody I know is asking to see how long somebody has had CWA installed since there are no significant conclusions that can be drawn from this information.

**Comment by dsarkar** [comment]
@v1nc @Ein-Tim @MikeMcC399 Thanks to everybody for contributing! 

---
Corona-Warn-App Open Source Team
